<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Energieträger – Argumentative Writing Units</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../energy-sources/part_energy-sources.html" rel="next">
<link href="../agriculture/part_agriculture.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../agriculture/part_agriculture.html">Fachübergreifende Lerneinheiten</a></li><li class="breadcrumb-item"><a href="../energy-carriers/part_energy-carriers.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Energieträger</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Argumentative Writing Units</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Lesemodus umschalten">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Argumentieren</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Konzeptualisierung</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Unterrichtseinbettung</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Innerfachliche Lerneinheiten</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Fachübergreifende Lerneinheiten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../agriculture/part_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ernährung und Ernährungsformen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../energy-carriers/part_energy-carriers.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Energieträger</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../energy-sources/part_energy-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Energiewandler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../plastic-pollution/part_plastic-pollution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Umweltverschmutzung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zusammenfassung</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#verkehr" id="toc-verkehr" class="nav-link active" data-scroll-target="#verkehr"><span class="header-section-number">3.1</span> Verkehr</a>
  <ul class="collapse">
  <li><a href="#kriterienübersicht" id="toc-kriterienübersicht" class="nav-link" data-scroll-target="#kriterienübersicht">Kriterienübersicht</a></li>
  <li><a href="#begrifflichkeiten" id="toc-begrifflichkeiten" class="nav-link" data-scroll-target="#begrifflichkeiten">Begrifflichkeiten</a></li>
  <li><a href="#kriterium-1-energiedichte" id="toc-kriterium-1-energiedichte" class="nav-link" data-scroll-target="#kriterium-1-energiedichte">Kriterium 1: Energiedichte</a></li>
  <li><a href="#kriterium-2-gesamtwirkungsgrad" id="toc-kriterium-2-gesamtwirkungsgrad" class="nav-link" data-scroll-target="#kriterium-2-gesamtwirkungsgrad">Kriterium 2: Gesamtwirkungsgrad</a></li>
  <li><a href="#kriterium-3-treibhausgasemissionen-bei-der-produktion" id="toc-kriterium-3-treibhausgasemissionen-bei-der-produktion" class="nav-link" data-scroll-target="#kriterium-3-treibhausgasemissionen-bei-der-produktion">Kriterium 3: Treibhausgasemissionen bei der Produktion</a></li>
  <li><a href="#kriterium-4-verfügbarkeit" id="toc-kriterium-4-verfügbarkeit" class="nav-link" data-scroll-target="#kriterium-4-verfügbarkeit">Kriterium 4: Verfügbarkeit</a></li>
  <li><a href="#kriterium-5-betrieb" id="toc-kriterium-5-betrieb" class="nav-link" data-scroll-target="#kriterium-5-betrieb">Kriterium 5: Betrieb</a></li>
  <li><a href="#kriterium-6-geräuschemissionen" id="toc-kriterium-6-geräuschemissionen" class="nav-link" data-scroll-target="#kriterium-6-geräuschemissionen">Kriterium 6: Geräuschemissionen</a></li>
  </ul></li>
  <li><a href="#frachtschifffahrt" id="toc-frachtschifffahrt" class="nav-link" data-scroll-target="#frachtschifffahrt"><span class="header-section-number">3.2</span> Frachtschifffahrt</a>
  <ul class="collapse">
  <li><a href="#kriterienübersicht-1" id="toc-kriterienübersicht-1" class="nav-link" data-scroll-target="#kriterienübersicht-1">Kriterienübersicht</a></li>
  <li><a href="#begrifflichkeiten-1" id="toc-begrifflichkeiten-1" class="nav-link" data-scroll-target="#begrifflichkeiten-1">Begrifflichkeiten</a></li>
  <li><a href="#kriterium-1-energiedichte-1" id="toc-kriterium-1-energiedichte-1" class="nav-link" data-scroll-target="#kriterium-1-energiedichte-1">Kriterium 1: Energiedichte</a></li>
  <li><a href="#kriterium-2-wirkungsgrad" id="toc-kriterium-2-wirkungsgrad" class="nav-link" data-scroll-target="#kriterium-2-wirkungsgrad">Kriterium 2: Wirkungsgrad</a></li>
  <li><a href="#kriterium-3-energiebedarf" id="toc-kriterium-3-energiebedarf" class="nav-link" data-scroll-target="#kriterium-3-energiebedarf">Kriterium 3: Energiebedarf</a></li>
  <li><a href="#kriterium-4-gefahrenpotenzial-und-toxizität" id="toc-kriterium-4-gefahrenpotenzial-und-toxizität" class="nav-link" data-scroll-target="#kriterium-4-gefahrenpotenzial-und-toxizität">Kriterium 4: Gefahrenpotenzial und Toxizität</a></li>
  <li><a href="#kriterium-5-lokale-treibhausgasemissionen-beim-betrieb" id="toc-kriterium-5-lokale-treibhausgasemissionen-beim-betrieb" class="nav-link" data-scroll-target="#kriterium-5-lokale-treibhausgasemissionen-beim-betrieb">Kriterium 5: Lokale Treibhausgasemissionen beim Betrieb</a></li>
  <li><a href="#kriterium-6-infrastruktur" id="toc-kriterium-6-infrastruktur" class="nav-link" data-scroll-target="#kriterium-6-infrastruktur">Kriterium 6: Infrastruktur</a></li>
  <li><a href="#kriterium-6-praxisreife" id="toc-kriterium-6-praxisreife" class="nav-link" data-scroll-target="#kriterium-6-praxisreife">Kriterium 6: Praxisreife</a></li>
  </ul></li>
  <li><a href="#biogas-vs.-erdgas" id="toc-biogas-vs.-erdgas" class="nav-link" data-scroll-target="#biogas-vs.-erdgas"><span class="header-section-number">3.3</span> Biogas vs.&nbsp;Erdgas</a>
  <ul class="collapse">
  <li><a href="#informationen-zu-erdgas" id="toc-informationen-zu-erdgas" class="nav-link" data-scroll-target="#informationen-zu-erdgas">Informationen zu Erdgas</a></li>
  <li><a href="#informationen-zu-biogas" id="toc-informationen-zu-biogas" class="nav-link" data-scroll-target="#informationen-zu-biogas">Informationen zu Biogas</a></li>
  <li><a href="#heizen-mit-biogas" id="toc-heizen-mit-biogas" class="nav-link" data-scroll-target="#heizen-mit-biogas">Heizen mit Biogas</a></li>
  <li><a href="#akzeptanz-biogas" id="toc-akzeptanz-biogas" class="nav-link" data-scroll-target="#akzeptanz-biogas">Akzeptanz Biogas</a></li>
  <li><a href="#durchschnittliche-gaskosten-für-haushalte" id="toc-durchschnittliche-gaskosten-für-haushalte" class="nav-link" data-scroll-target="#durchschnittliche-gaskosten-für-haushalte">Durchschnittliche Gaskosten für Haushalte</a></li>
  <li><a href="#strommix-deutschland-2023" id="toc-strommix-deutschland-2023" class="nav-link" data-scroll-target="#strommix-deutschland-2023">Strommix Deutschland 2023</a></li>
  <li><a href="#klimaschutzgesetz" id="toc-klimaschutzgesetz" class="nav-link" data-scroll-target="#klimaschutzgesetz">Klimaschutzgesetz</a></li>
  <li><a href="#vergleich-der-emissionen-ausgewählter-energieträger" id="toc-vergleich-der-emissionen-ausgewählter-energieträger" class="nav-link" data-scroll-target="#vergleich-der-emissionen-ausgewählter-energieträger">Vergleich der Emissionen ausgewählter Energieträger</a></li>
  <li><a href="#gasreserven-und-gasexporte" id="toc-gasreserven-und-gasexporte" class="nav-link" data-scroll-target="#gasreserven-und-gasexporte">Gasreserven und Gasexporte</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../agriculture/part_agriculture.html">Fachübergreifende Lerneinheiten</a></li><li class="breadcrumb-item"><a href="../energy-carriers/part_energy-carriers.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Energieträger</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Energieträger</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="verkehr" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="verkehr"><span class="header-section-number">3.1</span> Verkehr</h2>
<p>Die Treibhausgasemissionen des Personenverkehrs sollen drastisch reduziert werden, um die Klimaneutralität zu erreichen. Daher wird von der Politikerinnen und Politikern gefordert, dass Neuwagen mit einem Benzin- und Dieselmotor ab 2035 verboten werden. Konkret wird beraten, ob ein Umstieg auf Autos mit</p>
<ol type="1">
<li>Akkumulatoren,</li>
<li>Wasserstoff oder</li>
<li>E-Fuels (synthetische Kraftstoffe)</li>
</ol>
<p>als Energieträger gezielt gefördert werden soll.</p>
<p><strong>Diskutiere</strong> die genannten Energieträger vor dem Hintergrund des Klimawandels. Verwende insgesamt mindestens drei Kriterien aus den Materialien.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweise
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Empfiehl in deiner <strong>Einleitung</strong> eine Handlungsoption.</li>
<li>Formuliere in jedem <strong>Argument</strong> eine Behauptung aufbauend auf einem Kriterium, nenne passende Fakten und erkläre, warum die Fakten deine Behauptung stützen.</li>
<li>Berücksichtige in jedem <strong>Argument</strong> alle Handlungsoptionen.</li>
<li>Vergleiche in deinem <strong>Schluss</strong> die Bedeutsamkeit der Kriterien für deine Entscheidung.</li>
</ul>
</div>
</div>
<section id="kriterienübersicht" class="level3">
<h3 class="anchored" data-anchor-id="kriterienübersicht">Kriterienübersicht</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Kriterium</th>
<th style="text-align: left;">Akkumulatoren</th>
<th style="text-align: left;">Wasserstoff</th>
<th style="text-align: left;">E-Fuels (synthetische Kraftstoffe)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Energiedichte</td>
<td style="text-align: left;">≈ 0,88 MJ/kg</td>
<td style="text-align: left;">≈ 120 MJ/kg</td>
<td style="text-align: left;">≈ 46,4 MJ/kg</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gesamtwirkungs-<br>
grad</td>
<td style="text-align: left;">64 – 70%</td>
<td style="text-align: left;">25 – 28%</td>
<td style="text-align: left;">15 – 20%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Treibhausgas-<br>
emissionen<br>
bei der Produktion</td>
<td style="text-align: left;">≈ 13,1 t<br>
CO<sub>2</sub>-Äquivalente</td>
<td style="text-align: left;">≈ 13,6 t<br>
CO<sub>2</sub>-Äquivalente</td>
<td style="text-align: left;">≈ 7,8 t<br>
CO<sub>2</sub>-Äquivalente |</td>
</tr>
<tr class="even">
<td style="text-align: left;">Verfügbarkeit</td>
<td style="text-align: left;">Massenfertigung</td>
<td style="text-align: left;">Kleinserienfertigung</td>
<td style="text-align: left;">Massenfertigung</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Betrieb</td>
<td style="text-align: left;">Ladedauer: 30 min<br>
Reichweite: 400 km</td>
<td style="text-align: left;">Tankdauer: 3 min<br>
Reichweite: 700 km</td>
<td style="text-align: left;">Tankdauer: 3 min<br>
Reichweite: 700 km</td>
</tr>
<tr class="even">
<td style="text-align: left;">Geräusch-<br>
emissionen</td>
<td style="text-align: left;">≈ 57 dB bei 30 km/h</td>
<td style="text-align: left;">≈ 57 dB bei 30 km/h</td>
<td style="text-align: left;">≈ 61 dB bei 30 km/h</td>
</tr>
</tbody>
</table>
</section>
<section id="begrifflichkeiten" class="level3">
<h3 class="anchored" data-anchor-id="begrifflichkeiten">Begrifflichkeiten</h3>
<p>Alle drei Energieträger gelten als klimaneutral, sofern elektrische Energie aus erneuerbaren Energien genutzt wird.</p>
<p><strong>Akkumulatoren</strong> sind wiederaufladbare elektrochemische Zellen, die aktuell auf Basis von Lithium-Verbindungen hergestellt werden. Akkumulatoren können geladen werden, indem sie an das Stromnetz angeschlossen werden. Akkumulatoren können nur in speziell konzipierten Autos mit Elektromotor genutzt werden. In diesen Autos werden Akkumulatoren fest eingebaut, um einen Elektromotor zu betreiben. Bei der chemischen Reaktion, die im Akkumulator abläuft, wird kein Stoff freigesetzt.</p>
<p><strong>Wasserstoff</strong> ist ein Reinstoff, der unter Standardbedingungen als Gas vorliegt. Wasserstoff wird mittels Wasserelektrolyse hergestellt. Wasserstoff kann nur in speziell konzipierten Autos mit Brennstoffzelle und Elektromotor genutzt werden. In diesen Autos wird Wasserstoff in Drucktanks transportiert und in einer Brennstoffzelle mit Sauerstoff umgesetzt, um einen Elektromotor zu betreiben. Bei der chemischen Reaktion, die in der Brennstoffzelle abläuft, entsteht als Produkt Wasser.</p>
<p><strong>E-Fuels</strong> sind Stoffgemische aus Kohlenwasserstoffen, die unter Standardbedingungen als Flüssigkeit vorliegen. E-Fuels werden aus Wasserstoff und Kohlenstoffdioxid, das der Atmosphäre entnommen wird, hergestellt. E-Fuels können in konventionellen Autos mit Verbrennungsmotor genutzt werden. In diesen Autos werden E-Fuels in Flüssigkeitstanks transportiert und in Verbrennungsmotoren mit Sauerstoff umgesetzt. Bei der Verbrennungsreaktion, die im Motorraum abläuft, entsteht als Produkt u. a. Kohlenstoffdioxid. Insgesamt wird der Atmosphäre bei der Synthese genauso viel Kohlenstoffdioxid entnommen, wie bei der Verbrennung freigesetzt wird.</p>
</section>
<section id="kriterium-1-energiedichte" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-1-energiedichte">Kriterium 1: Energiedichte</h3>
<p>Die Energiedichte gibt an, wie viel Energie pro Masse eines Stoffes bzw. eines Systems gespeichert werden kann. Die Energiedichte ist der maßgebliche Faktor für die Masse eines Energiespeichers (hier Tank bzw. Akkumulator). Je höher die massenbezogene Energiedichte, desto mehr Energie kann bei gleicher Masse gespeichert werden. Der Einsatz von Energieträger mit einer höheren Energiedichte könnte somit u. a. die Konstruktion von Autos mit geringerer Masse oder größerer Reichweite ermöglichen.</p>
</section>
<section id="kriterium-2-gesamtwirkungsgrad" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-2-gesamtwirkungsgrad">Kriterium 2: Gesamtwirkungsgrad</h3>
<p>Der Gesamtwirkungsgrad beziffert, wie effizient die elektrische Energie der erneuerbaren Energien zum Autofahren genutzt wird. In die Berechnung des Gesamtwirkungsgrads fließt der gesamte Prozess von der Bereitstellung der Energie (bspw. durch Windenergieanlagen) bis zur Nutzung beim Autofahren ein (genauer: Verhältnis aus “genutzter” Bewegungsenergie und zugeführter elektrischer Energie). Je höher der Gesamtwirkungsgrad ist, desto weniger Energie wird während des Prozesses an die Umgebung abgegeben. Je niedriger der Gesamtwirkungsgrad ist, desto mehr elektrische Energie muss bereitgestellt werden, um dieselbe Strecke zu fahren.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cars-crit1-battery" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cars-crit1-battery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_cars_fig_crit1_battery.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cars-crit1-battery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.1: Energieflussdiagramm von Bereitstellung der elektrischen Energie bis zum Antrieb des Autos
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bei mit <strong>Akkumulator</strong> betriebenen Autos wird die elektrische Energie direkt zum Laden des Akkumulators genutzt. Der Akkumulator wird zum Betrieb des Elektromotors genutzt.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cars-crit1-hydro" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cars-crit1-hydro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_cars_fig_crit1_hydro.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cars-crit1-hydro-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.2: Energieflussdiagramm von der Synthese des Wasserstoffs bis zum Antrieb des Autos
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bei mit <strong>Wasserstoff</strong> betriebenen Autos wird die elektrische Energie genutzt, um Wasserstoff mittels Wasserelektrolyse zu erzeugen. Der Wasserstoff reagiert mit Sauerstoff in der Brennstoffzelle des Autos. Hierbei wird chemische in elektrische Energie umgewandelt, sodass der Elektromotor betrieben werden kann.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cars-crit1-e-fuels" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cars-crit1-e-fuels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_cars_fig_crit1_e-fuels.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cars-crit1-e-fuels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.3: Energieflussdiagramm von der Synthese der E-Fuels bis zum Antrieb des Autos
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bei mit <strong>E-Fuels</strong> betriebenen Autos wird Wasserstoff, der durch Wasserelektrolyse bereitgestellt wird, mit Kohlenstoffdioxid, das aus der Umgebungsluft gefiltert wird, zu E-Fuels umgesetzt. E-Fuels werden zum Betrieb des Verbrennungsmotors genutzt.</p>
</section>
<section id="kriterium-3-treibhausgasemissionen-bei-der-produktion" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-3-treibhausgasemissionen-bei-der-produktion">Kriterium 3: Treibhausgasemissionen bei der Produktion</h3>
<p>CO<sub>2</sub>-Äquivalente ist eine Größe zur Vereinheitlichung der Klimawirkung der unterschiedlichen Treibhausgase und wird in der Einheit Tonne (t) angegeben. Die Produktion von Autos ist ein energieintensiver Prozess, bei dem Treibhausgase emittiert werden. In die Kalkulation der Treibhausgasemissionen gehen die Emission bei der Gewinnung und Aufbereitung der Rohstoffe sowie deren Weiterverarbeitung im Herstellungsprozess der Autos mit ein.</p>
<p>Bei mit <strong>Akkumulator</strong> betriebenen Autos entfällt ein Großteil der Treibhausgasemissionen auf die Aufbereitung von Lithium und die Herstellung des Akkumulators. Je größer der Akkumulator ist, desto mehr Treibhausgase werden emittiert. Bei Klein- und Mittelwagen entfallen mehr Treibhausgasemissionen auf die Herstellung eines mit Wasserstoff betriebenen Autos mit Brennstoffzelle als auf eines mit Akkumulator (s. Tabelle). Auf die Herstellung eines Autos der Oberklasse mit Akkumulator entfallen jedoch mehr Treibhausgasemissionen (18,6 t CO<sub>2</sub>-Äquivalent) als auf ein mit Wasserstoff betriebenes Auto mit Brennstoffzelle (13,5 t CO<sub>2</sub>-Äquivalent).</p>
<p>Bei mit <strong>Wasserstoff</strong> betriebenen Autos entfällt ein Großteil der Treibhausgasemissionen auf die Aufbereitung von Platin und die Herstellung der Brennstoffzelle. Der zusätzliche Akkumulator fällt hier wesentlich kleiner aus.</p>
<p>Bei mit <strong>E-Fuels</strong> betriebenen Autos entfällt ein Großteil der Treibhausgasemissionen auf die Aufbereitung von Platin und Palladium und die Herstellung des Verbrennungsmotors sowie des Katalysators.</p>
</section>
<section id="kriterium-4-verfügbarkeit" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-4-verfügbarkeit">Kriterium 4: Verfügbarkeit</h3>
<p>Mit <strong>Akkumulator</strong> betriebene Autos werden bereits in Massenproduktion von fast allen Herstellern produziert und verkauft.</p>
<p>Mit <strong>Wasserstoff</strong> betriebene Autos werden nur von einigen wenigen Herstellern und in nur sehr begrenzter Anzahl weiterentwickelt und produziert. In Deutschland werden insgesamt nur zwei verschiedene Modelle verkauft. Viele Hersteller entwickeln derzeit keine Wasserstoffautos.</p>
<p>Mit <strong>E-Fuels</strong> können alle konventionellen Autos mit Verbrennungsmotor betrieben werden. Diese Autos werden im großen Maßstab von fast allen namhaften Herstellern weiterentwickelt, produziert und verkauft. Zudem könnten bereits gekaufte Autos weiterverwendet werden.</p>
</section>
<section id="kriterium-5-betrieb" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-5-betrieb">Kriterium 5: Betrieb</h3>
<p>Wichtige Faktoren für den Betrieb eines Autos sind dessen Reichweite und die Tank- bzw. Ladedauer. Im Mittel unternehmen Personen in Deutschland drei Fahrten pro Tag mit dem Auto, wobei sie zwischen 30 und 40 Kilometer zurücklegen. Nur ca. 1 % aller Autofahrten ist länger als 100 Kilometer. Im Mittel sind Autos mehr als 23 Stunden am Tag geparkt, davon über 20 Stunden am Wohnort.</p>
</section>
<section id="kriterium-6-geräuschemissionen" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-6-geräuschemissionen">Kriterium 6: Geräuschemissionen</h3>
<p>Autos, die mit <strong>Akkumulator</strong> und mit <strong>Wasserstoff</strong> betrieben werden, weisen die gleichen Geräuschemissionen auf. Bei niedrigen Geschwindigkeiten unter 30 km/h liegen diese unter 57 dB. Bei höheren Geschwindigkeiten überwiegt die Geräuschentwicklung durch Rollreibung und Windwiderstand.</p>
<p>Autos, die mit <strong>E-Fuels</strong> betrieben werden, weisen bei niedrigen Geschwindigkeiten unter 30 km/h schon Geräuschemissionen von ca. 61 dB auf. Diese sind u. a. auf die Geräuschentwicklung des Verbrennungsmotors zurückzuführen. Insbesondere beim Anfahren, bspw. an Ampeln, treten höhere Geräuschemissionen auf. Bei höheren Geschwindigkeiten hat die Geräuschentwicklung durch Rollreibung und Windwiderstand eine zunehmend größere Bedeutung.</p>
<p>Lärm ist ein Stressfaktor und hat negative Auswirkungen auf die Gesundheit, da es das autonome Nervensystem und das hormonelle System aktiviert. Straßenlärm kann zu Schlafstörungen, Bluthochdruck führen und steigert das Herzinfarkt-Risiko um bis zu 20 – 30%.</p>
</section>
</section>
<section id="frachtschifffahrt" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="frachtschifffahrt"><span class="header-section-number">3.2</span> Frachtschifffahrt</h2>
<p>Die Schifffahrt ist für ungefähr 2,5 % der weltweiten Treibhausgasemissionen verantwortlich. Damit erzeugt die Schifffahrt fast 1,5-mal so viele Treibhausgasemissionen wie Deutschland. Die EU will die Treibhausgasemissionen in der Schifffahrt bis 2050 um 80 % gegenüber 2020 verringern. Daher wird von den Politikerinnen und Politikern gefordert, dass neu gebaute Frachtschiffe statt Schiffsdiesel alternative Energieträger verwenden müssen. Konkret wird beraten, ob ein Umstieg auf Frachtschiffe mit</p>
<ol type="1">
<li>Ammoniak,</li>
<li>Methanol oder</li>
<li>Wasserstoff</li>
</ol>
<p>als Energieträger gezielt gefördert werden soll.</p>
<p><strong>Diskutiere</strong> die genannten Energieträger vor dem Hintergrund des Klimawandels. Verwende insgesamt mindestens drei Kriterien aus den Materialien.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweise
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Empfiehl in deiner <strong>Einleitung</strong> eine Handlungsoption.</li>
<li>Formuliere in jedem <strong>Argument</strong> eine Behauptung aufbauend auf einem Kriterium, nenne passende Fakten und erkläre, warum die Fakten deine Behauptung stützen.</li>
<li>Berücksichtige in jedem <strong>Argument</strong> alle Handlungsoptionen.</li>
<li>Vergleiche in deinem <strong>Schluss</strong> die Bedeutsamkeit der Kriterien für deine Entscheidung.</li>
</ul>
</div>
</div>
<section id="kriterienübersicht-1" class="level3">
<h3 class="anchored" data-anchor-id="kriterienübersicht-1">Kriterienübersicht</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Kriterium</th>
<th style="text-align: left;">Ammoniak</th>
<th style="text-align: left;">Methanol</th>
<th style="text-align: left;">Wasserstoff</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Energiedichte</td>
<td style="text-align: left;">≈ 11,5 MJ/l</td>
<td style="text-align: left;">≈ 15,6 MJ/l</td>
<td style="text-align: left;">≈ 8,5 MJ/l</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gesamtwirkungsgrad</td>
<td style="text-align: left;">27 %</td>
<td style="text-align: left;">22 %</td>
<td style="text-align: left;">23 %</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Energiebedarf</td>
<td style="text-align: left;">117 – 177TWh</td>
<td style="text-align: left;">154 – 232TWh</td>
<td style="text-align: left;">117 – 141TWh</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gefahrenpotenzial<br>
und Toxizität</td>
<td style="text-align: left;">Hoch</td>
<td style="text-align: left;">Mittel</td>
<td style="text-align: left;">Mittel</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lokale Treibhausgas-<br>
emissionen beim Betrieb</td>
<td style="text-align: left;">Stickoxide</td>
<td style="text-align: left;">Kohlenstoffdioxid</td>
<td style="text-align: left;">Keine</td>
</tr>
<tr class="even">
<td style="text-align: left;">Infrastruktur für<br>
die Lagerung</td>
<td style="text-align: left;">Gut ausgebaut</td>
<td style="text-align: left;">Wenig ausgebaut</td>
<td style="text-align: left;">Nicht ausgebaut</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Praxisreife der<br>
Antriebssysteme</td>
<td style="text-align: left;">Mittel</td>
<td style="text-align: left;">Hoch</td>
<td style="text-align: left;">Mittel</td>
</tr>
</tbody>
</table>
</section>
<section id="begrifflichkeiten-1" class="level3">
<h3 class="anchored" data-anchor-id="begrifflichkeiten-1">Begrifflichkeiten</h3>
<p><strong>Ammoniak</strong> (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mtext mathvariant="normal">NH</mtext><mn>3</mn></msub><annotation encoding="application/x-tex">\text{NH}_3</annotation></semantics></math>) ist unter Standardbedingungen gasförmig (Siedepunkt von -33 °C). Ammoniak wird im industriellen Maßstab in einem chemischen Verfahren (Haber-Bosch-Verfahren) aus Wasserstoff und Stickstoff synthetisiert. Hierzu muss zunächst Wasserstoff bspw. durch Elektrolyse von Wasser gewonnen und Stickstoff aus der Luft abgetrennt werden. Anschließend findet die Synthese des Ammoniaks unter einem hohen Druck von ca. 300 bar, bei 450 °C in einem Reaktor statt. Ein Katalysator (bspw. aus Eisen) beschleunigt hierbei die Reaktion. Ammoniak kann im Schiffsantrieb sowohl direkt in Verbrennungsmotoren als auch in Brennstoffzellen, welche chemische in elektrische Energie umwandeln, eingesetzt werden. Mithilfe der chemischen Energie kann dann ein Elektromotor betrieben werden. Bei der chemischen Reaktion des Ammoniaks mit Sauerstoff entstehen Stickstoff und Wasser.</p>
<p><strong>Methanol</strong> (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mtext mathvariant="normal">CH</mtext><mn>3</mn></msub><mtext mathvariant="normal">OH</mtext></mrow><annotation encoding="application/x-tex">\text{CH}_3\text{OH}</annotation></semantics></math>) ist unter Standardbedingungen flüssig (Siedepunkt von 65 °C). Methanol kann aus Wasserstoff und Kohlenstoffmonoxid und Kohlenstoffdioxid synthetisiert werden. Insgesamt lässt sich die Herstellung des Methanols in die Schritte der Synthesegasherstellung (Elektrolyse von Wasser, Abtrennung von Kohlenstoffdioxid aus der Luft), Methanolsynthese und Aufbereitung durch Destillation unterteilen. Das Methanol kann im Schiffsantrieb in Verbrennungsmotoren eingesetzt werden. Bei der chemischen Reaktion des Methanols mit Sauerstoff entstehen Kohlenstoffdioxid und Wasser. Daher kann der Einsatz von Methanol nur klimaneutral sein, wenn bei der Erzeugung des Methanols keine fossilen Energieträger genutzt werden.</p>
<p><strong>Wasserstoff</strong> (<math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><annotation encoding="application/x-tex">\text{H}_2</annotation></semantics></math>) ist unter Standardbedingungen gasförmig (Siedepunkt von -252 °C). Wasserstoff kann mittels Elektrolyse aus Wasser erzeugt werden. Die Erzeugung von Wasserstoff soll zukünftig in großtechnischem Maßstab in Elektrolyseuren stattfinden. Als Elektrolyseur bezeichnet man eine Vorrichtung, die eine chemische Reaktion mithilfe von Strom herbeiführt. Wasserstoff kann im Schiffsantrieb in Brennstoffzellen eingesetzt werden. Die Brennstoffzelle wandelt im Wasserstoff gespeicherten chemischen Energie in elektrische Energie um. Mithilfe der chemischen Energie kann dann ein Elektromotor betrieben werden. Bei der chemischen Reaktion des Wasserstoffs mit Sauerstoff entsteht Wasser. Um Wasserstoff klimaneutral herzustellen, muss der Strom aus erneuerbaren Energien verwendet werden.</p>
</section>
<section id="kriterium-1-energiedichte-1" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-1-energiedichte-1">Kriterium 1: Energiedichte</h3>
<p>Die volumetrische Energiedichte gibt die gespeicherte Energiemenge pro Volumen an. Feste und flüssige Energieträger weisen eine höhere volumetrische Energiedichte als gasförmige Energieträger auf. Der Einsatz von Energieträgern mit einer höheren volumetrischen Energiedichte ermöglicht somit eine effizientere Mitführung auf Schiffen, da weniger Frachtraum verloren geht. Alle drei alternativen Energieträger (Ammoniak, Methanol, Wasserstoff) besitzen geringere volumetrische Energiedichten als Schiffsdiesel oder Schweröl und nehmen daher bei dem Transport und bei der Lagerung mehr Volumen bei gleicher Energiemenge ein.</p>
<p><strong>Ammoniak</strong> muss verflüssigt werden, um ihn platzsparend speichern zu können. Dies liegt daran, dass Ammoniak bei Standardbedingungen gasförmig ist. Da der Siedepunkt von Ammoniak bei -33 °C liegt, kann bei geringer Kompressionsarbeit eine Verflüssigung erreicht werden. Die Kompressionsarbeit beträgt ca. 1 % der Energiemenge, die zur Herstellung von Ammoniak benötigt wird. Herkömmliche Schiffe müssten mit neuen Tanks ausgestattet werden, welche mehr Platz als Tanks für Methanol, jedoch weniger Platz als Tanks für Wasserstoff einnehmen würden.</p>
<p><strong>Methanol</strong> liegt bei Standardbedingungen bereits flüssig vor, da der Siedepunkt 65 °C beträgt. Daher kann Methanol direkt in herkömmlichen Schiffstanks gespeichert werden. Trotzdem müssten bestehende Schiffe mit zusätzlichen Tanks ausgerüstet werden, da die volumetrische Energiedichte von Methanol geringer als diejenige von Schiffsdiesel oder Schweröl ist. Trotzdem würden die Tanks weniger Platz einnehmen als Tanks für Ammoniak oder Wasserstoff.</p>
<p><strong>Wasserstoff</strong> muss verflüssigt werden, um ihn platzsparend speichern zu können. Dies liegt daran, dass Wasserstoff bei Standardbedingungen gasförmig ist. Da der Siedepunkt von Wasserstoff mit -255 °C sehr gering ist, muss zur Verflüssigung ein hoher Druck mit bis zu 700 Bar erzeugt werden. Daher muss eine hohe Kompressionsarbeit zur Verflüssigung geleistet werden. Die Kompressionsarbeit beträgt ca. 25 % der Energiemenge, die zur Herstellung von Ammoniak benötigt wird. Schiffe müssten mit neuen Tanks ausgerüstet werden, welche mehr Platz als die Tanks für Ammoniak oder Methanol einnehmen würden.</p>
</section>
<section id="kriterium-2-wirkungsgrad" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-2-wirkungsgrad">Kriterium 2: Wirkungsgrad</h3>
<p>Der Wirkungsgrad gibt an, welcher Anteil der zugeführten Energie bei einem Prozess in die gewünschte Energieform umgewandelt wird. Für die Schifffahrt bedeutet dies, dass je höher der Gesamtwirkungsgrad ist, desto größer ist der Anteil der erneuerbaren Energie, der auch tatsächlich für den Vortrieb des Frachtschiffs genutzt wird. Der Gesamtwirkungsgrad für die Schifffahrt berechnet sich aus dem Wirkungsgrad der Herstellung (Synthese), der Transformation bspw. der Verflüssigung durch Kompression (bei Ammoniak und Wasserstoff), des Transports sowie der Effizienz des Schiffsantriebs.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cargo-ships-crit2-efficiency" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cargo-ships-crit2-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="part_energy-carriers_files/figure-html/fig-cargo-ships-crit2-efficiency-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cargo-ships-crit2-efficiency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.4: Wirkungsgrad von der Synthese des Energieträgers bis zum Antrieb eines Frachtschiffs
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="kriterium-3-energiebedarf" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-3-energiebedarf">Kriterium 3: Energiebedarf</h3>
<p>Der Energiebedarf gibt an, wie viel Energie benötigt würde, um die gesamte Frachtschiffsflotte der EU und Großbritannien mit dem jeweiligen Energieträger zu versorgen. Die Angabe erfolgt in Terawattstunden pro Jahr.</p>
<p><strong>Ammoniak</strong> wird mittels Haber-Bosch-Verfahren aus Stickstoff und Wasserstoff synthetisiert. Hier ist insbesondere die Wasserstofferzeugung mittels Elektrolyse, sowie die endotherme Synthese von Ammoniak aus Wasserstoff und Stickstoff energieintensiv. Derzeit existieren nicht ausreichend Elektrolyseure für die Erzeugung von Wasserstoff. Die Synthese von Ammoniak ist gut erprobt und wird bereits im in einem industriellen Maßstab durchgeführt. Für die Versorgung der gesamten Frachtschiffsflotte in der EU und Großbritannien würden je nach Antrieb zwischen 117 – 177TWh elektrische Energie pro Jahr benötigt.</p>
<p><strong>Methanol</strong> wird aus Kohlenstoffdioxid und Wasserstoff synthetisiert. Sowohl Wasserstofferzeugung mittels Elektrolyse sowie die Abtrennung von Kohlenstoffdioxid aus der Atmosphäre sind energieintensiv. Die Abtrennung von Kohlenstoffdioxid aus der Atmosphäre wird in absehbarer Zeit nicht großtechnisch durchgeführt werden. Für die Versorgung der gesamten Frachtschiffsflotte in der EU und Großbritannien würden je nach Antrieb zwischen 154 – 232TWh elektrische Energie pro Jahr benötigt.</p>
<p><strong>Wasserstoff</strong> wird mittels Elektrolyse gewonnen. Dieses Verfahren ist energieintensiv und derzeit existieren nicht ausreichend Elektrolyseure für die Erzeugung von Wasserstoff. Für die Versorgung der gesamten Frachtschiffsflotte in der EU und Großbritannien würden je nach Antrieb zwischen 117 und 141 TWh elektrische Energie pro Jahr benötigt.</p>
</section>
<section id="kriterium-4-gefahrenpotenzial-und-toxizität" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-4-gefahrenpotenzial-und-toxizität">Kriterium 4: Gefahrenpotenzial und Toxizität</h3>
<p>Bei einem Austritt des flüssigen <strong>Ammoniaks</strong> in die Umgebung verdampft dieser und verbreitet sich schnell in der Umgebung. Zu der Entflammung von Ammoniak ist eine sehr hohe Aktivierungsenergie notwendig, weswegen Ammoniakdämpfe allgemein im Freien keine Brandgefahr darstellen. Für Lagertanks, welche kontinuierlicher hoher Wärmeeinwirkung ausgesetzt sind, besteht jedoch eine Explosionsgefahr. Bei Menschen ruft das Einatmen von hohen Konzentrationen an Ammoniak unmittelbare Verbrennungen der Nasenschleimhaut, des Rachens und der Atemwege hervor. Ammoniak kann die Atemwege und Lunge schädigen und eine schwerwiegende Exposition zu Atemstillstand führen. Gelangt Ammoniak in größeren Mengen in die Umwelt, schädigt es die Ökosysteme. So ist Ammoniak für viele Wasserlebewesen toxisch. Ammoniak kann die Artenzusammensetzung in einem Ökosystem beeinflussen oder zur gänzlichen Auslöschung einzelner Arten in dem kontaminierten Gebiet führen.</p>
<p>Bei einem Austritt von flüssigem <strong>Methanol</strong> in die Umgebung findet zum Teil eine Verdunstung statt. Zur Entflammung von Methanol ist eine niedrige Aktivierungsenergie notwendig. Aufgrund der hohen Entzündlichkeit von Methanol geht von jeglichen Zündquellen ein hohes Risiko aus. Für Menschen ist Methanol giftig, da es irreversible Nervenschäden verursachen kann. So kann die Einnahme zur Erblindung der sogar zum Tod führen, was bei der vorschriftsmäßigen Verwendung als Treibstoff jedoch unwahrscheinlich ist. Im Falle eines Austritts in die Umgebung löst sich Methanol rasch im Meerwasser. Durch die Ausbreitung von Methanol geht jedoch nur eine geringe Gefahr für Ökosysteme aus, da es eine geringe Giftigkeit für Wasserorganismen besitzt. Zudem ist Methanol biologisch abbaubar und hat kein Potenzial zur Bioakkumulation.</p>
<p>Bei einem Austritt von flüssigem <strong>Wasserstoff</strong> verdampft dieser und verbreitet sich schnell in der Umgebung. Zu der Entflammung von Wasserstoff ist eine niedrige Aktivierungsenergie nötig. Wasserstoff weist also eine leichte Entzündbarkeit auf. Wasserstoff reagiert heftig mit Sauerstoff und starken Oxidationsmitteln. Vor allem durch Wärmezufuhr kann der hochreaktive Wasserstoff schnell Brände und Explosionen auslösen. Für Menschen ist Wasserstoff ein ungiftiges Gas. Erst bei einer bewussten Aufnahme einer hohen Menge von Wasserstoff kann es eine erstickende Wirkung für Menschen haben. Durch die Emission von Wasserstoff geht keine Gefahr für die Umwelt aus.</p>
</section>
<section id="kriterium-5-lokale-treibhausgasemissionen-beim-betrieb" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-5-lokale-treibhausgasemissionen-beim-betrieb">Kriterium 5: Lokale Treibhausgasemissionen beim Betrieb</h3>
<p><strong>Ammoniak</strong> ist eine kohlenstofffreie Verbindung, weshalb bei der Reaktion mit Sauerstoff in der Brennstoffzelle keine Kohlenstoffdioxidemissionen anfallen.</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>4</mn><msub><mtext mathvariant="normal">NH</mtext><mn>3</mn></msub><mo>+</mo><mn>3</mn><msub><mtext mathvariant="normal">O</mtext><mn>2</mn></msub><mo>→</mo><mn>2</mn><msub><mtext mathvariant="normal">N</mtext><mn>2</mn></msub><mo>+</mo><mn>6</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex"> 4\text{NH}_3 + 3\text{O}_2 \rightarrow 2\text{N}_2 + 6\text{H}_2\text{O} </annotation></semantics></math></p>
<p>Bei der Verwendung in Verbrennungsmotoren kommt es jedoch zu Stickstoffdioxidemissionen. Stickstoffdioxid ist ein starkes Treibhausgas.</p>
<p><strong>Methanol</strong> ist eine kohlenstoffhaltige Verbindung, welche bei der Reaktion mit Sauerstoff Kohlenstoffdioxid freisetzt. Kohlenstoffdioxid ist ein Treibhausgas.</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>2</mn><msub><mtext mathvariant="normal">CH</mtext><mn>3</mn></msub><mtext mathvariant="normal">OH</mtext><mo>+</mo><mn>3</mn><mtext mathvariant="normal">O</mtext><mn>2</mn><mo>→</mo><mn>2</mn><msub><mtext mathvariant="normal">CO</mtext><mn>2</mn></msub><mo>+</mo><mn>4</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex">2 \text{CH}_3\text{OH} + 3 \text{O}2 \rightarrow 2 \text{CO}_2 + 4 \text{H}_2\text{O}</annotation></semantics></math></p>
<p><strong>Wasserstoff</strong> ist eine kohlenstofffreie Verbindung. Bei der Umsetzung in Brennstoffzellen entstehen keine Treibhausgasemissionen.</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>2</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mo>+</mo><msub><mtext mathvariant="normal">O</mtext><mn>2</mn></msub><mo>→</mo><mn>2</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex">2 \text{H}_2 + \text{O}_2 \rightarrow  2\text{H}_2\text{O}</annotation></semantics></math></p>
</section>
<section id="kriterium-6-infrastruktur" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-6-infrastruktur">Kriterium 6: Infrastruktur</h3>
<p>Es gibt bereits eine gute ausgebaute Infrastruktur zur Lagerung von <strong>Ammoniak</strong>, da Ammoniak ein Ausgangsstoff für die Düngemittelherstellung ist. Zudem gibt es weltweit bereits 156 bestehende Ammoniakterminals. Für LNG (liquefied natural gas, also verflüssigtes Erdgas) bestimmte Terminals könnten durch nur leichte Anpassungen für Ammoniak nutzbar gemacht werden. Mittels Onshore (über Land) und Offshore (Unterwasser) Pipelines können auch derzeit schon mittlere Transportdistanzen überwunden werden.</p>
<p>Die Infrastruktur für die Lagerung von <strong>Methanol</strong> ist nur geringfügig ausgebaut, jedoch ist eine Umrüstung bestehender Infrastruktur möglich, da es 117 Methanol Terminals weltweit gibt. 47 der Häfen verfügen über Lagerkapazitäten von mehr als 50.000 Tonnen. Um die zusätzliche Nachfrage nach Methanol zur Verwendung als Schiffskraftstoff zu decken sind vermutlich größere oder zusätzliche Terminals notwendig. Es gibt verschiedene Möglichkeiten die Schiffe mit dem Methanol zu betanken. Entweder transportieren Lkws den Kraftstoff zum Schiff, oder eine Betankung kann z.B. durch ein Bunkerschiff erfolgen. Dies ist eine gängige Methode, da hier größere Mengen als per Lkw betankt werden können. Für Schiffe, die vom Heimathafen aus operieren oder feste Route befahren, ist eine Betankung über Terminals oder Pipelines üblich.</p>
<p>Es gibt keine ausgebaute Infrastruktur für die Lagerung von <strong>Wasserstoff</strong>. Wasserstoff erfordert wegen seiner chemischen und physikalischen Eigenschaften eines hohen Sicherheitsstandards. Aktuell gibt es in Deutschland auch schon drei Wasserstoffnetze, die allerdings eine regionale Begrenzung aufweisen. Auch könnte das deutsche Erdgasnetz nach einzelnen Änderungen genutzt werden. Zukünftig soll Wasserstoff aber als “grüner” Energieträger für die Industrie eingesetzt werden, sodass davon auszugehen ist, dass die Infrastruktur stark ausgebaut wird. Erste Projekte hierzu laufen gerade an und werden u. a. stark von der EU gefördert. In Hamburg soll zukünftig ein Hub für grünen Wasserstoff entstehen, da der Standort von bestehender Infrastruktur profitiert. Dieser soll ab 2050 in Betrieb genommen werden.</p>
</section>
<section id="kriterium-6-praxisreife" class="level3">
<h3 class="anchored" data-anchor-id="kriterium-6-praxisreife">Kriterium 6: Praxisreife</h3>
<p>Eine kommerzielle Verfügbarkeit für ein Antriebssystem für <strong>Ammoniak</strong> ist aktuell bislang nicht gegeben. Die ausgereifteste und günstigste Möglichkeit, ein Schiff mit Ammoniak zu betreiben, sind herkömmliche Viertakt-Verbrennungsmotor. Als Abgase würden jedoch Wasserdampf und das starke Treibhausgas Stickstoffdioxid entstehen. Der klimaneutrale Antrieb mittels Hochdruck-Brennstoffzellen wird aktuell in ersten Versorgungs- und Frachtschiffen getestet bspw. in Norwegen getestet. Das erste kommerziell eingesetze, mit Ammoniak betriebene Frachtschiff, soll 2026 seine Dienst aufnehmen.</p>
<p>Es besteht eine kommerzielle Verfügbarkeit von Antriebssysteme für <strong>Methanol</strong> in Form eines Verbrennungsmotors. Die bis 2022 weltweit größte Redereei Maersk nahm im Januar 2024 das erste mit Methanol betriebene Frachtschiff in seine Flotte auf.</p>
<p>Es besteht keine kommerzielle Verfügbarkeit des Antriebssystems für <strong>Wasserstoff</strong>, jedoch existieren Prototypen. Als Schlüsseltechnologie werden wasserstoffbetriebene Brennstoffzellen beschrieben, wie sie bspw. in U-Booten eingesetzt werden. Seit ca. 2021 gibt es erste Binnenfrachschiffe, die mit Wasserstoff betrieben werden.</p>
</section>
</section>
<section id="biogas-vs.-erdgas" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="biogas-vs.-erdgas"><span class="header-section-number">3.3</span> Biogas vs.&nbsp;Erdgas</h2>
<p>Infolge der Energiewende und dem damit verbundenen Ausstieg aus der Kohlenkraft und Kernenergie wird in der deutschen Politik über den zukünftigen Strommix beraten. Neben der Nutzung von Strom aus Photovoltaik, Windenergie und der Wasserkraft wird auch noch immer Gas zur Stromerzeugung für die Industrie und Haushalte und für den Betrieb von Gasheizungen benötigt. Befürworter der Nutzung von Biogas sprechen sich dafür aus, das fossile Erdgas vollständig durch Biogas zu ersetzen. Diskutiere den Ersatz von Erdgas durch Biogas unter Verwendung derMaterialien. Ergänze deine Argumentation gerne um eigene Punkte.</p>
<p><strong>Diskutiere</strong> den Ersatz von Erdgas durch Biogas unter Verwendung der Materialien. Ergänze deine Argumentation um eigene Punkte.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hinweise
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Empfiehl in deiner <strong>Einleitung</strong> eine Handlungsoption.</li>
<li>Formuliere in jedem <strong>Argument</strong> eine Behauptung aufbauend auf einem Kriterium, nenne passende Fakten und erkläre, warum die Fakten deine Behauptung stützen.</li>
<li>Berücksichtige in jedem <strong>Argument</strong> alle Handlungsoptionen.</li>
<li>Vergleiche in deinem <strong>Schluss</strong> die Bedeutsamkeit der Kriterien für deine Entscheidung.</li>
</ul>
</div>
</div>
<section id="informationen-zu-erdgas" class="level3">
<h3 class="anchored" data-anchor-id="informationen-zu-erdgas">Informationen zu Erdgas</h3>
<p>Erdgas ist ein brennbares Gasgemisch, das in unterirdischen Lagerstätten vorkommt. Es ist ähnlich wie Erdöl ein fossiler Rohstoff, der über einen viele Millionen Jahren andauernden Abbauprozess aus großen Mengen organischen Ausgangsstoffen wie marinen Kleinstlebewesen entstanden ist. Erdgas wird zum Beispiel zum Heizen, für thermische Prozesse, zur Stromerzeugung, als Treibstoff oder als Edukt in der Industrie genutzt. Erdgas kann als Gas mit Pipelines oder verflüssigt als LNG per Schiff transportiert werden. Schätzungen, wie lange es dauert, bis die Erdgasreserven erschöpft sind, variieren stark und sind abhängig von der jährlich genutzten Menge. Viele Experten schätzen die Dauer auf etwa 50 bis 100 Jahre.</p>
<p>Die Zusammensetzung von Erdgas variiert je nach Förderstätte. Der Hauptbestandteil von Erdgas ist jedoch immer Methan (CH<sub>4</sub>). Erdgas enthält zudem auch größere Anteile anderer Stoffe. Hierzu gehören andere gasförmige Kohlenwasserstoffe wie Ethan (C<sub>2</sub>H<sub>6</sub>), Ethen (C<sub>2</sub>H<sub>4</sub>), Propan (C<sub>3</sub>H<sub>8</sub>) oder Butan (C<sub>4</sub>H<sub>10</sub>). Außerdem enthalten ist beispielsweise das giftige Gas Schwefelwasserstoff (H<sub>2</sub>S) und bis zu neun Prozent Kohlenstoffdioxid (CO<sub>2</sub>), welches bei der Förderung von Erdgas in die Luft ausgestoßen wird. Zudem entweichen bei der Förderung durchschnittlich 2,95 % des gesamten geförderten Methans ungenutzt in die Atmosphäre.</p>
<p>Das im Erdgas enthaltene Methan wird beim Heizen oder bei der Stromerzeugung verbrannt. Hierbei läuft folgende Reaktion ab:</p>
<p>Wortgleichung:</p>
<div data-text-align="center">
<p>Methan + Sauerstoff <math display="inline" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mo>→</mo><annotation encoding="application/x-tex">\rightarrow</annotation></semantics></math> Kohlenstoffdioxid + Wasser</p>
</div>
<p>Reaktionsgleichung:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mtext mathvariant="normal">CH</mtext><mn>4</mn></msub><mo>+</mo><msub><mtext mathvariant="normal">O</mtext><mn>2</mn></msub><mo>→</mo><msub><mtext mathvariant="normal">CO</mtext><mn>2</mn></msub><mo>+</mo><mn>2</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex">\text{CH}_{4} + \text{O}_{2} \rightarrow \text{CO}_{2} + 2\text{H}_{2}\text{O}</annotation></semantics></math></p>
</section>
<section id="informationen-zu-biogas" class="level3">
<h3 class="anchored" data-anchor-id="informationen-zu-biogas">Informationen zu Biogas</h3>
<p>Bei Biogas handelt es sich um einen Energieträger, der aus erneuerbaren Rohstoffen gewonnen wird. Es wird in Deutschland bereits in etwa 9600 Anlagen hergestellt. Etwa 56 % des Gases wird hierbei aus Mais hergestellt. Andere Ausgangsstoffe sind Gras, Getreide und Zuckerrüben. Insbesondere der Maisanbau für die Biogasherstellung steht aufgrund des Aufkommens von Monokulturen in der Kritik. Hierdurch wird die Artenvielfalt gefährdet. Bereits 2022 wurden 9 % der Landwirtschaftsflächen Deutschlands für die Biogasherstellung genutzt, die somit beispielsweise nicht für den Anbau von Lebensmitteln bereitstehen. Alternativ kann Biogas auch aus Lebensmittel- und Ernteresten, Gülle und Mist hergestellt werden. Hierbei wird bisher nur etwa ein Drittel des vorhandenen Potenzials genutzt. Branchenverbände haben berechnet, dass die vollständige Nutzung solcher Abfälle jährlich 140 Terrawattstunden Energie liefern könnte. Auch die Nutzung alternativer Energiepflanzen wie Wildpflanzen, die eine Reihe ökologischer Vorteile, wie die Bereitstellung eines Lebensraumes für Insekten, Vögel und Wildtiere bereitstellen, ist denkbar. Generell bieten die zur Herstellung von Biogas verwendeten Pflanzen den Vorteil, dass diese während des Wachstums Kohlenstoffdioxid aus der Luft aufnehmen.</p>
<p>Biogas besteht zu etwa 50 – 66% aus Methan (CH<sub>4</sub>). Weitere Bestandteile sind Kohlenstoffdioxid (CO<sub>2</sub>), Stickstoff (N<sub>2</sub>), Wasserstoff (H<sub>2</sub>), Schwefelwasserstoff (H<sub>2</sub>S) und Ammoniak (NH<sub>3</sub>). Die beiden zuletzt genannten Stoffe müssen aus dem Biogas entfernt werden, da sie Menschen und Maschinen schaden können. Etwa 5 % des in Biogasanlagen produzierten Methans entweicht unkontrolliert in die Atmosphäre.</p>
<p>Das Gas entsteht durch die Vergärung der Ausgangsstoffe in einem luftdichten Reaktor mithilfe von Bakterien. Bei etwa 40 °C wirken die Bakterien optimal und bauen pflanzliche und tierische Stoffe ab. Der Prozess findet unter Ausschluss von Licht und Sauerstoff unter dauerhaftem Umrühren statt. Der wichtigste Vorgang bei diesem Prozess ist die Entstehung von Methan. Dies kann auf zwei Arten geschehen. Einerseits aus einer Aufspaltung von Essigsäure in Methan und Kohlenstoffdioxid:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mtext mathvariant="normal">CH</mtext><mn>3</mn></msub><mtext mathvariant="normal">COOH</mtext><mo>→</mo><msub><mtext mathvariant="normal">CH</mtext><mn>4</mn></msub><mo>+</mo><mn>2</mn><msub><mtext mathvariant="normal">CO</mtext><mn>2</mn></msub></mrow><annotation encoding="application/x-tex">\text{CH}_{3}\text{COOH} \rightarrow \text{CH}_{4} + 2\text{CO}_{2}</annotation></semantics></math></p>
<p>und andererseits aus der Reaktion von Kohlenstoffdioxid und Wasserstoff zu Methan und Wasser:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mtext mathvariant="normal">CO</mtext><mn>2</mn></msub><mo>+</mo><mn>4</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mo>→</mo><msub><mtext mathvariant="normal">CH</mtext><mn>4</mn></msub><mo>+</mo><mn>2</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex"> \text{CO}_{2} + 4 \text{H}_{2} \rightarrow \text{CH}_{4} + 2 \text{H}_{2}\text{O}</annotation></semantics></math></p>
<p>Wird Biogas verbrannt, so entstehen ebenso wie beim Erdgas Kohlenstoffdioxid und Wasser. Hierbei läuft folgende Reaktion ab:</p>
<p>Wortgleichung: Methan + Sauerstoff → Kohlenstoffdioxid + Wasser</p>
<p>Reaktionsgleichung:</p>
<p><math display="block" xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><msub><mtext mathvariant="normal">CH</mtext><mn>4</mn></msub><mo>+</mo><msub><mtext mathvariant="normal">O</mtext><mn>2</mn></msub><mo>→</mo><msub><mtext mathvariant="normal">CO</mtext><mn>2</mn></msub><mo>+</mo><mn>2</mn><msub><mtext mathvariant="normal">H</mtext><mn>2</mn></msub><mtext mathvariant="normal">O</mtext></mrow><annotation encoding="application/x-tex"> \text{CH}_{4} + \text{O}_{2} \rightarrow \text{CO}_{2} + 2\text{H}_{2}\text{O}</annotation></semantics></math></p>
</section>
<section id="heizen-mit-biogas" class="level3">
<h3 class="anchored" data-anchor-id="heizen-mit-biogas">Heizen mit Biogas</h3>
<p>Herkömmliche Gasheizungen lassen sich nicht direkt mit Biogas betreiben. Hierzu muss Biogas zunächst zu Biomethan verarbeitet werden. Hierzu erfolgt zunächst eine Biogasaufbereitung, bei der Kohlenstoffdioxid und andere Bestandteile durch verschiedene technische Verfahren abgetrennt werden. Das so entstehende Biogas ist chemisch gleichzusetzen mit Erdgas und kann somit ins Erdgasnetz eingespeist werden.</p>
<p>Technologien für die Aufbereitung von Biogas zu Biomethan sind bekannt und verfügbar. Jedoch bemängeln Experten, dass es zu wenige solche Anlagen in Deutschland gibt. Denn nur rund 250 der 9600 Biogasanlagen in Deutschland sind mit einer solchen Technologie ausgestattet. Ein Ausbau der Infrastruktur würde große Mengen Geld kosten.</p>
</section>
<section id="akzeptanz-biogas" class="level3">
<h3 class="anchored" data-anchor-id="akzeptanz-biogas">Akzeptanz Biogas</h3>
<p>Eine Umfrage konnten zeigen, dass 89 % der Bürgerinnen und Bürger die stärkere Nutzung von Erneuerbaren Energien in Deutschland befürwortet. Hierbei befürworten 64 % solche Anlagen in der Nachbarschaft zu haben. Es gibt jedoch auch Untersuchungen, die zeigen, dass es begrenzten lokalen Widerstand gegen Biogasanlagen in einem Umkreis von 2 Kilometern gibt. Gegner befürchten insbesondere Gestank, Lärm, Gift im Wasser und volle Straßen. Auch die Intensität des Maisanbaus und die Größe der gebauten Biogasanlagen. wirkt sich negativ auf die Akzeptanz aus</p>
</section>
<section id="durchschnittliche-gaskosten-für-haushalte" class="level3">
<h3 class="anchored" data-anchor-id="durchschnittliche-gaskosten-für-haushalte">Durchschnittliche Gaskosten für Haushalte</h3>
<p>Die folgende Tabelle zeigt die durchschnittlichen Kosten eines vierköpfigen Haushalts für Biogas und Erdgas bei einem jährlichen Verbrauch von 15.000 kWh. (Stand April 2024)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Energieträger</th>
<th style="text-align: left;">Durchschnittliche Kosten pro Jahr in Euro</th>
<th style="text-align: left;">Durchschnittlicher Preis pro kWh in Euro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Erdgas</td>
<td style="text-align: left;">1.263</td>
<td style="text-align: left;">0,084</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biogas</td>
<td style="text-align: left;">2.246</td>
<td style="text-align: left;">0,150</td>
</tr>
</tbody>
</table>
</section>
<section id="strommix-deutschland-2023" class="level3">
<h3 class="anchored" data-anchor-id="strommix-deutschland-2023">Strommix Deutschland 2023</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-lng-fig-strommix" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-lng-fig-strommix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_lng_fig_strommix.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-lng-fig-strommix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.5: Die Abbildung zeigt die in Deutschland im Jahr 2023 durch verschiedene Methoden hergestellten Mengen an Strom in Terrawattstunden (TWh).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="klimaschutzgesetz" class="level3">
<h3 class="anchored" data-anchor-id="klimaschutzgesetz">Klimaschutzgesetz</h3>
<p>Im Juni 2023 hat die Bundesregierung eine Neufassung des Klimaschutzgesetzes beschlossen. Dieses Gesetz stellt den Kern der nationalen Klimapolitik dar. Es regelt, dass Deutschland in den kommenden Jahren den Ausstoß an Treibhausgasen wie Kohlenstoffdioxid und Methan immer weiter reduzieren muss und bis 2045 treibhausgasneutral sein soll. Dies bedeutet nicht, dass ab dem Zeitpunkt gar keine Treibhausgase mehr ausgestoßen werden dürfen, sondern dass Ausstöße durch Klimaschutzprojekte ausgeglichen oder beispielsweise unterirdisch gespeichert werden müssen.</p>
</section>
<section id="vergleich-der-emissionen-ausgewählter-energieträger" class="level3">
<h3 class="anchored" data-anchor-id="vergleich-der-emissionen-ausgewählter-energieträger">Vergleich der Emissionen ausgewählter Energieträger</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-lng-fig-emissionsfaktoren" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-lng-fig-emissionsfaktoren-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_lng_fig_emissionsfaktoren.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-lng-fig-emissionsfaktoren-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.6: Die Grafik zeigt die Emissionsfaktoren verschiedener Energieträger.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Der Emissionsfaktor wird dafür genutzt, die verschiedenen Emissionen der unterschiedlichen Energieträger vergleichbar zu machen. Hierzu werden alle ausgestoßenen Treibhausgase in Kohlenstoffdioxid-Äquivalente umgerechnet. Der Emissionsfaktor gibt an, wie viele Gramm Kohlenstoffdioxid-Äquivalente pro erzeugter Kilowattstunde Energie freigesetzt werden. Je höher dieser Wert liegt, desto mehr tragen die Emissionen eines Energieträgers zum Klimawandel bei.</p>
</section>
<section id="gasreserven-und-gasexporte" class="level3">
<h3 class="anchored" data-anchor-id="gasreserven-und-gasexporte">Gasreserven und Gasexporte</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-lng-fig-erdgasreserven" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-lng-fig-erdgasreserven-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_lng_fig_erdgasreserven.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-lng-fig-erdgasreserven-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.7: Die Grafik zeigt die zehn Länder mit den größten bestätigten Gasreserven im Jahr 2021. Zum Vergleich: Deutschlands Erdgasreserven betragen etwa 20 km<sup>3</sup>.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-lng-fig-erdgasexporteure" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-lng-fig-erdgasexporteure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_lng_fig_erdgasexporteure.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-lng-fig-erdgasexporteure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.8: Die Grafik zeigt die zehn größten Gas-Exporteure weltweit.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-task-lng-fig-erdgasimporte" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-task-lng-fig-erdgasimporte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="task_lng_fig_erdgasimporte.png" class="img-fluid figure-img" alt="A diagram displaying the data science cycle with communicate highlighed in blue. ">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-task-lng-fig-erdgasimporte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;3.9: Die Grafik zeigt die Länder, aus denen Deutschland im Jahr 2023 Erdgas importierte. Die Erdgasexporte der verschiedenen Länder werden in Terrawattstunden (TWh) angegeben. LNG-Importe per Schiff stammen vor allem aus den USA.
</figcaption>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../agriculture/part_agriculture.html" class="pagination-link" aria-label="Ernährung und Ernährungsformen">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ernährung und Ernährungsformen</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../energy-sources/part_energy-sources.html" class="pagination-link" aria-label="Energiewandler">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Energiewandler</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>