<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Umweltverschmutzung – Argumentative Writing Units</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../summary.html" rel="next">
<link href="../energy-sources/part_energy-sources.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>


</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../agriculture/part_agriculture.html">Fachübergreifende Lerneinheiten</a></li><li class="breadcrumb-item"><a href="../plastic-pollution/part_plastic-pollution.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Umweltverschmutzung</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Argumentative Writing Units</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Lesemodus umschalten">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Argumentieren</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Konzeptualisierung</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Unterrichtseinbettung</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Innerfachliche Lerneinheiten</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Fachübergreifende Lerneinheiten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../agriculture/part_agriculture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Ernährung und Ernährungsformen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../energy-carriers/part_energy-carriers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Energieträger</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../energy-sources/part_energy-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Energiewandler</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../plastic-pollution/part_plastic-pollution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Umweltverschmutzung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zusammenfassung</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliographie</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#pet-alternativen" id="toc-pet-alternativen" class="nav-link active" data-scroll-target="#pet-alternativen"><span class="header-section-number">5.1</span> PET Alternativen</a>
  <ul class="collapse">
  <li><a href="#aufgabenstellung" id="toc-aufgabenstellung" class="nav-link" data-scroll-target="#aufgabenstellung">Aufgabenstellung</a></li>
  <li><a href="#begrifflichkeiten" id="toc-begrifflichkeiten" class="nav-link" data-scroll-target="#begrifflichkeiten">Begrifflichkeiten</a></li>
  <li><a href="#polymilchsäure" id="toc-polymilchsäure" class="nav-link" data-scroll-target="#polymilchsäure">Polymilchsäure</a></li>
  <li><a href="#polyhydroxyalkanoate" id="toc-polyhydroxyalkanoate" class="nav-link" data-scroll-target="#polyhydroxyalkanoate">Polyhydroxyalkanoate</a></li>
  <li><a href="#kriterien" id="toc-kriterien" class="nav-link" data-scroll-target="#kriterien">Kriterien</a></li>
  <li><a href="#verwendete-rohstoffe" id="toc-verwendete-rohstoffe" class="nav-link" data-scroll-target="#verwendete-rohstoffe">Verwendete Rohstoffe</a></li>
  <li><a href="#flächenbedarf-der-rohstoffe" id="toc-flächenbedarf-der-rohstoffe" class="nav-link" data-scroll-target="#flächenbedarf-der-rohstoffe">Flächenbedarf der Rohstoffe</a></li>
  <li><a href="#wasserbedarf-der-rohstoffe" id="toc-wasserbedarf-der-rohstoffe" class="nav-link" data-scroll-target="#wasserbedarf-der-rohstoffe">Wasserbedarf der Rohstoffe</a></li>
  <li><a href="#alternative-produktion" id="toc-alternative-produktion" class="nav-link" data-scroll-target="#alternative-produktion">Alternative Produktion</a></li>
  <li><a href="#biologische-abbaubarkeit" id="toc-biologische-abbaubarkeit" class="nav-link" data-scroll-target="#biologische-abbaubarkeit">Biologische Abbaubarkeit</a></li>
  <li><a href="#energiebedarf" id="toc-energiebedarf" class="nav-link" data-scroll-target="#energiebedarf">Energiebedarf</a></li>
  <li><a href="#treibhauspotential" id="toc-treibhauspotential" class="nav-link" data-scroll-target="#treibhauspotential">Treibhauspotential</a></li>
  </ul></li>
  <li><a href="#pet-und-alternativen" id="toc-pet-und-alternativen" class="nav-link" data-scroll-target="#pet-und-alternativen"><span class="header-section-number">5.2</span> PET und Alternativen</a>
  <ul class="collapse">
  <li><a href="#aufgabenstellung-1" id="toc-aufgabenstellung-1" class="nav-link" data-scroll-target="#aufgabenstellung-1">Aufgabenstellung</a></li>
  <li><a href="#kriterienüberischt" id="toc-kriterienüberischt" class="nav-link" data-scroll-target="#kriterienüberischt">Kriterienüberischt</a></li>
  <li><a href="#verwendete-rohstoffe-1" id="toc-verwendete-rohstoffe-1" class="nav-link" data-scroll-target="#verwendete-rohstoffe-1">Verwendete Rohstoffe</a></li>
  <li><a href="#flächenbedarf-der-rohstoffe-1" id="toc-flächenbedarf-der-rohstoffe-1" class="nav-link" data-scroll-target="#flächenbedarf-der-rohstoffe-1">Flächenbedarf der Rohstoffe</a></li>
  <li><a href="#wasserbedarf-der-rohstoffe-1" id="toc-wasserbedarf-der-rohstoffe-1" class="nav-link" data-scroll-target="#wasserbedarf-der-rohstoffe-1">Wasserbedarf der Rohstoffe</a></li>
  <li><a href="#alternative-produktion-1" id="toc-alternative-produktion-1" class="nav-link" data-scroll-target="#alternative-produktion-1">Alternative Produktion</a></li>
  <li><a href="#biologische-abbaubarkeit-1" id="toc-biologische-abbaubarkeit-1" class="nav-link" data-scroll-target="#biologische-abbaubarkeit-1">Biologische Abbaubarkeit</a></li>
  <li><a href="#energiebedarf-1" id="toc-energiebedarf-1" class="nav-link" data-scroll-target="#energiebedarf-1">Energiebedarf</a></li>
  <li><a href="#treibhauspotential-1" id="toc-treibhauspotential-1" class="nav-link" data-scroll-target="#treibhauspotential-1">Treibhauspotential</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../agriculture/part_agriculture.html">Fachübergreifende Lerneinheiten</a></li><li class="breadcrumb-item"><a href="../plastic-pollution/part_plastic-pollution.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Umweltverschmutzung</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Umweltverschmutzung</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="pet-alternativen" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pet-alternativen"><span class="header-section-number">5.1</span> PET Alternativen</h2>
<section id="aufgabenstellung" class="level3">
<h3 class="anchored" data-anchor-id="aufgabenstellung">Aufgabenstellung</h3>
<p>Die Produktion von Kunststoffen hat in den letzten Jahrzehnten stark zugenommen und ist von 1,7 Millionen Tonnen im Jahr 1950 auf 367 Millionen Tonnen im Jahr 2020 gestiegen. Ein Teil des Plastikmülls gelangt in die Umwelt und führt dazu, dass jährlich über 1 Millionen Meeresbewohner verenden. Im Jahr 2021 produzierten Einwohner in Deutschland pro Person ca. 41 kg Verpackungsmüll aus Kunststoff. Viele Verpackungen bestehen aus Polyethylenterephthalat (PET). Plastik ist in der Natur nicht vollständig abbaubar, sondern zersetzt sich in immer kleinere Partikel. Das entstandene Mikroplastik kann über Gewässer in die Nahrungskette gelangen und der Mensch nimmt es z. B. durch den Verzehr von Fisch auf. Im Mittel nimmt jeder Mensch laut einer Studie pro Woche 5 Gramm Mikroplastik – das ist ungefähr das Gewicht einer Kreditkarte – auf.</p>
<p>Die Entwicklung und der Einsatz von nachhaltigen Plastik-Alternativen werden also immer ausschlaggebender. Aktuell wird darüber diskutiert, welcher biobasierter Kunststoff gefördert werden soll.</p>
<p>Konkret wird beraten, ob</p>
<ol type="a">
<li>Polymilchsäure (PLA) oder</li>
<li>Polyhydroxyalkanoate (PHA)</li>
</ol>
<p>verstärkt für die Produktion von Kunststoff-Alternativen gefördert werden soll.</p>
<p>Diskutieren Sie die vorgeschlagenen Kunststoff-Alternativen vor dem Hintergrund der Nachhaltigkeit auf der Basis von mindestens drei Kriterien aus den Materialien der folgenden Seiten. Stärken Sie Ihre Argumente, indem Sie die Relevanz der Kriterien für Ihre Behauptungen erklären.</p>
</section>
<section id="begrifflichkeiten" class="level3">
<h3 class="anchored" data-anchor-id="begrifflichkeiten">Begrifflichkeiten</h3>
<p>Im Allgemeinen werden Biokunststoffe aus erneuerbaren Ressourcen hergestellt und es werden keine fossilen Brennstoffe verwendet. Konventionelles Plastik wird aus Rohöl hergestellt, was eine begrenzte Ressource ist. Kunststoff-Alternativen können verwendet werden, um Umweltproblemen entgegenzuwirken, welche beispielsweise durch die unsachgemäße Entsorgung von Plastikmüll entstehen. Im Gegensatz zu konventionellen Kunststoffen können Biokunststoffe zersetzt werden und die Einleitung von schädlichen Chemikalien in die Natur kann reduziert werden.</p>
<p>Bei der Verwendung des Begriffs Biokunststoff ist zu beachten, dass er Materialien umfasst, die entweder aus nachwachsenden Rohstoffen (Biomasse) hergestellt werden, kompostierbar/biologisch abbaubar sind oder beide Eigenschaften besitzen.</p>
<p>Laut Definition kann ein biobasiertes/biogenes Produkt vollständig oder teilweise aus Biomasse bestehen. Das heißt, dass Mischstoffe aus biobasierten und auch erdölbasierten Kunststoffen unter diesen Begriff fallen. Hier wird davon ausgegangen, dass die biobasierten Kunststoffe zu 100 % aus pflanzlichen Rohstoffen produziert wurden.</p>
</section>
<section id="polymilchsäure" class="level3">
<h3 class="anchored" data-anchor-id="polymilchsäure">Polymilchsäure</h3>
<p>PLA ist ein Polyester, das aus nachwachsenden und natürlichen Rohstoffen hergestellt wird und industriell kompostiert werden kann. Es zählt zu den meist eingesetzten und vielversprechendsten Materialien für Kunststoff-Alternativen. Als Ausgangsmaterialien werden stärkereiche landwirtschaftliche Nebenprodukte und Produkte verwendet. Polymilchsäure wird produziert, indem Stärke extrahiert wird und mit Hilfe von Enzymen in Glucose umgewandelt wird. Mikroorganismen fermentieren Glucose in Milchsäure, die dann in Polylactid umgewandelt werden. PLA kann also durch Polykondensation von Milchsäure oder durch Polymerisation hergestellt werden.</p>
</section>
<section id="polyhydroxyalkanoate" class="level3">
<h3 class="anchored" data-anchor-id="polyhydroxyalkanoate">Polyhydroxyalkanoate</h3>
<p>Polyhydroxyalkanoate sind Polyester, die ebenfalls aus natürlichen Rohstoffen hergestellt werden. Dies geschieht durch die Fermentation von Zuckern und Lipiden. Die Biopolymere werden von verschiedenen Mikroorganismen produziert und dienen ihnen als Speicherstoffe. Nachdem die Mikroorganismen im Nährmedium kultiviert wurden und eine bestimmte Zelldichte erreicht haben, werden Mangelbedingungen und ein Überschuss an Kohlenstoff eingestellt. Dadurch werden die Biopolyester im Cytoplasma synthetisiert und in Form von Körnchen (Granula) in den Zellen akkumuliert.</p>
<p>Auch PHA wird weit verbreitet eingesetzt und scheint aussichtsreich zu sein. Polyhydroxybutyrat (PHB) ist der bekannteste Vertreter innerhalb der PHA Familie.</p>
</section>
<section id="kriterien" class="level3">
<h3 class="anchored" data-anchor-id="kriterien">Kriterien</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 27%">
<col style="width: 34%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Kriterium</strong></td>
<td><strong>Polymilchsäure (PLA)</strong></td>
<td><strong>Polyhydroxyalkanoate (PHA)</strong></td>
</tr>
<tr class="even">
<td>Menge benötigter Rohstoffe</td>
<td>2,39 t bis 11,31 t pro 1 t PLA</td>
<td>4,63 t bis 22 t pro 1 t PHB</td>
</tr>
<tr class="odd">
<td>Flächenbedarf der Rohstoffe</td>
<td>0,16 ha bis 1,04 ha pro 1 t PLA</td>
<td>0.30 ha bis 1.88 ha pro 1 t PHB</td>
</tr>
<tr class="even">
<td>Wasserbedarf der Rohstoffe</td>
<td>1215 m<sup>3</sup> bis 6 468 m<sup>3</sup> pro 1 t PLA</td>
<td>2364 m<sup>3</sup> bis 12867 m<sup>3</sup> pro 1 t PHB</td>
</tr>
<tr class="odd">
<td>Alternative Herstellung</td>
<td>in genetisch veränderte <em>Escherichia coli</em></td>
<td>PHB in Cyanobakterien</td>
</tr>
<tr class="even">
<td>Biologische Abbaubarkeit</td>
<td><p>Temperatur: 58 °C</p>
<p>Abbaubarkeit: 85 – 90 %</p>
<p>Dauer: 65 Tage</p></td>
<td><p>Temperatur: 30 – 35 °C</p>
<p>Abbaubarkeit: 20 – 28 %</p>
<p>Dauer: 28 Tage</p></td>
</tr>
<tr class="odd">
<td>Energiebedarf</td>
<td>57 MJ/kg</td>
<td>45 MJ/kg</td>
</tr>
<tr class="even">
<td>Treibhauspotential</td>
<td>3,8 kg CO<sub>2</sub>e pro kg PLA</td>
<td>3 kg CO<sub>2</sub>e pro kg PHA</td>
</tr>
</tbody>
</table>
</section>
<section id="verwendete-rohstoffe" class="level3">
<h3 class="anchored" data-anchor-id="verwendete-rohstoffe">Verwendete Rohstoffe</h3>
<p>Zur Herstellung von PLA können unterschiedliche Kohlenhydratquellen als Ausgangsstoffe verwendet werden. So kann neben Pflanzenöl der Zucker aus Zuckerrohr oder Zuckerrüben oder Stärke aus z. B. Mais oder Weizen verwendet werden.</p>
<p>Die Menge an benötigtem Rohstoff ist mit 2,39 t Mais am geringsten und mit 11,31 t Zuckerrohr am höchsten um 1 t PLA herzustellen. Vergleicht man diese Werte mit den notwendigen Mengen der gleichen Rohstoffe für die Herstellung von 1 t PHB, fallen diese geringer aus. Für die Herstellung von PHB wird also etwas mehr Rohstoff gebraucht. Für 1 t PHB werden beispielsweise 4,63 t Mais und 22 t vom Zuckerrohr eingesetzt. Dennoch bestimmt der verwendete, am jeweils besten geeignete Rohstoff, ob für die PLA- oder PHB-Produktion letztlich verwendet wird. Bei der Herstellung von Zucker entstehen beim Auspressen von Zuckerrohr faserige</p>
<p>Überreste. Diese gemahlenen Fasern werden weiterverarbeitet. Zuckerrohr ist ein schnell nachwachsender Rohstoff, der sowohl kälte- als auch hitzebeständig sowie geschmacksneutral ist. Diese faserigen Überreste bilden die Grundlage für verschiedene biobasierte Kunststoffe. Produkte, die aus diesen Resten hergestellt werden, sind daher nachhaltig und der Ertrag ist hoch, weil aus 100 Tonnen Zuckerrohr mehr als dreimal so viel faseriges Material gewonnen werden kann wie Zucker.</p>
<p>Die Vielfalt der Ausgangsstoffe ermöglicht eine flexible und anpassungsfähige Produktion, je nach den lokalen Bedingungen. Dennoch ist es wichtig, möglichst wenig Rohstoffe zu verwenden, damit diese nicht an anderer Stelle wie in der Lebensmittelbranche oder im Futtermittelsektor fehlen. Um der Belastung der Anbauflächen entgegenzuwirken und die Umwelt zu schonen, ist die Verwendung von Reststoffen empfehlenswert.</p>
</section>
<section id="flächenbedarf-der-rohstoffe" class="level3">
<h3 class="anchored" data-anchor-id="flächenbedarf-der-rohstoffe">Flächenbedarf der Rohstoffe</h3>
<p>Die benötigte Fläche für Rohstoffe, welche für eine Tonne PLA benötigt werden, unterscheidet sich leicht von der Fläche, die für eine Tonne PHB beansprucht wird. Der Flächenbedarf wird in Hektar (ha) angegeben. Um 1 t PLA zu produzieren, wird 0,16 ha (Zuckerrohr) bis 1,04 ha (Weizen) Fläche benötigt, um die erforderliche Menge des jeweiligen Rohstoffes anzubauen. Hingegen wird für die Herstellung von PHB eine Fläche von 0.30 ha (Zuckerrohr) bis 1.88 ha (Weizen) benötigt.</p>
<p>Die landwirtschaftliche Nutzfläche in der Europäischen Union beträgt ca. 174 Millionen ha. Im Vergleich dazu würden z. B. die zur Zeit erzeugten 100.000 t PLA-Fasern mit 16.000 ha (Zuckerrohr) bis 100.000 ha (Weizen) eine geringe Fläche einnehmen.</p>
<p>Im Mittel nimmt die Produktion von PLA im Vergleich zu PHA weniger Fläche in Anspruch. Somit können auch der Verlust der biologischen Vielfalt und die Belastung der Böden geringer ausfallen. Es ist wichtig zu beachten, dass durch die Herstellung von Biokunststoffen eine Konkurrenz zwischen Anbauflächen für Rohstoffe für Alternative-Kunststoffe und Anbauflächen für Nahrungsmittel entstehen könnte. Die Verwendung von Reststoffen könnte diesem Problem aber entgegenwirken. Es könnte umweltschonend und nachhaltig gewirtschaftet werden, wenn nur Reste von Rohstoffen eingesetzt werden, die ansonsten verbrannt werden würden.</p>
</section>
<section id="wasserbedarf-der-rohstoffe" class="level3">
<h3 class="anchored" data-anchor-id="wasserbedarf-der-rohstoffe">Wasserbedarf der Rohstoffe</h3>
<p>Auch die benötigte Menge an Wasser, die für die Herstellung der Rohstoffe benötigt wird, unterscheidet sich zwischen Polymilchsäure und Polyhydroxybutyrat. Der Wasserverbrauch wird in Kubikmetern angegeben. Für die Herstellung von einer Tonne PLA sind 1215 m<sup>3</sup> (Zuckerrübe) bis 6468 m<sup>3</sup> (Weizen) Wasser notwendig. Hingegen werden 2364 m<sup>3</sup> (Zuckerrübe) bis 12867 m<sup>3</sup> (Weizen) Wasser verwendet, um die Rohstoffe für die gleiche Menge PHB zu produzieren.</p>
<p>Diese große Menge an Wasser kann durch eine alternative Produktion von PHB durch Cyanobakterien vermieden werden. Die Cyanobakterien benötigen keine intensive Bewässerung, wie der Anbau der Rohstoffe zur Produktion von PLA und PHA/PHB. So können Cyanobakterien in Abwassern wachsen und anfallender Stickstoff und Phosphat können zur Kultivierung genutzt werden. Auf diese Weise kann eine beträchtliche Menge an Süßwasser gespart werden. Diese Art der Herstellung von PHB verringert den Druck auf Gewässer, da keine landwirtschaftlichen Flächen benötigt werden, auf denen Pestizide eingesetzt werden, die anschließend ins Grundwasser gelangen. Zudem trägt dieser Ansatz zu einer effektiven Kreislaufwirtschaft bei, da die vorhandenen Nährstoffe im Abwasser genutzt werden. Indirekt kann durch diese Produktionsweise auch zum Klimaschutz beigetragen werden, da weniger kohlenstoffspeichernde Ökosysteme (z. B. Regenwälder) gerodet werden müssen.</p>
</section>
<section id="alternative-produktion" class="level3">
<h3 class="anchored" data-anchor-id="alternative-produktion">Alternative Produktion</h3>
<p>Zudem besteht die Möglichkeit, auf die zuvor genannten Rohstoffe zu verzichten und durch den Einsatz von Bakterien Biokunststoff zu produzieren. <em>Escherichia coli</em> (<em>E. coli</em>) Bakterien können PLA direkt aus Traubenzucker herstellen. Dafür müssen die Organismen allerdings genetisch verändert werden. Zudem ist die Konzentration des erzeugten PLAs noch zu gering für eine industrielle Anwendung. Auch PHB kann in Bioreaktoren durch heterotrophe Bakterien wie <em>Cupriavidus necator</em> und ebenfalls durch genetisch veränderte <em>E. coli</em> hergestellt werden. Hier ist allerdings der Nachteil, dass für die Fermentationsprozesse immer noch viel organischer Kohlenstoff (z. B. Glucose) notwendig ist. Alternativ besteht die Möglichkeit, Cyanobakterien unter Nährstoffmangel für die Herstellung kleiner Mengen von PHB einzusetzen. Sie können durch die Fotosynthese Licht als Energie nutzen und dabei CO<sub>2</sub> (Kohlenstoffdioxid) binden. So kann PHB auf eine nachhaltige Weise produziert werden und Flächen und Rohstoffe gespart werden. Dadurch wird die Umwelt geschont und auch die Effizienz kann durch die Produktion unter kontrollierten Bedingungen in Bioreaktoren gesteigert werden. Die dezentrale Einsetzbarkeit von Bioreaktoren reduziert die Transportwege. Obwohl diese Art der Produktion planbarer und stabiler ist als die Nutzung landwirtschaftlicher Rohstoffe, ist die Herstellung von genetisch veränderten Organismen zeitaufwendig und kostenintensiv.</p>
</section>
<section id="biologische-abbaubarkeit" class="level3">
<h3 class="anchored" data-anchor-id="biologische-abbaubarkeit">Biologische Abbaubarkeit</h3>
<p>Biologische Abbaubarkeit bedeutet, dass ein Stoff in CO<sub>2</sub>, CH<sub>4</sub> (Methan), Wasser, Biomasse und anorganische Verbindungen zersetzt werden kann. Für einen erfolgreichen Abbau müssen aber bestimmte Bedingungen vorherrschen, wie beispielsweise höhere Temperaturen, auch können Enzyme oder Mikroorganismen hinzugefügt werden. Es bedeutet also nicht, dass diese Materialien natürlich abbaubar sind und auf dem heimischen Kompost verrotten können.</p>
<p>PLA lässt sich bei Temperaturen von ca. 58 °C und einer hohen Luftfeuchtigkeit von über 98 % biologisch abbaubar. Die Polymilchsäure wird durch Hydrolyse gespalten und anschließend durch Mikroorganismen zersetzt. Die biologische Abbaubarkeit beträgt 85-90 % innerhalb von ungefähr 65 Tagen. Im Meerwasser kann PLA fast nicht abgebaut werden und es wurden bereits durch PLA-Mikropartikel ausgelöste Stoffwechselveränderungen bei Miesmuscheln nachgewiesen. Hingegen können verschiedene PHAs in 28 Tagen beispielsweise zu 61 % (PHB) zersetzt werden. Zudem wurde nach Abbau keine Toxizität festgestellt und Testorganismen waren zu 100 % lebensfähig. Auch die Kompostiertemperatur von PHA hingegen ist mit Temperaturen 30-35 °C geringer. Ungefähr 20 bis 28 % können in 28 Tagen zersetzt werden.</p>
<p>Eine schnelle Abbaubarkeit ist wichtig, da das Vorkommen in der Umwelt Tiere und Pflanzen belastet. Je schneller ein Material abgebaut wird, desto geringer ist die Wahrscheinlichkeit, dass es zu Mikroplastik zerfällt und in Nahrungsketten gelangt. Die Abbaubarkeit in natürlichen Umgebungen von PHB und vor allem PLA ist aber deutlich eingeschränkt. Die hohen benötigten Temperaturen für den Abbau in der Kompostieranlage verbrauchen Energie und könnten bei Nutzung nicht erneuerbarer Energiequellen den Klimawandel fördern. Da die erforderliche Temperatur für den Abbau von PLA höher ist, ist es wahrscheinlich, dass sich dessen Verwendung schädlicher auf das Klima auswirkt.</p>
</section>
<section id="energiebedarf" class="level3">
<h3 class="anchored" data-anchor-id="energiebedarf">Energiebedarf</h3>
<p>Ein anderer wichtiger Faktor, um die Umweltauswirkungen besser einschätzen zu können, ist der Energiebedarf. Angegeben ist der Bedarf an Energie aus nicht erneuerbaren Quellen, welcher notwendig ist, um 1 kg des jeweiligen biobasierten Kunststoffes herzustellen. Der Energiebedarf wird in Megajoule (MJ) angegeben. Erdölbasierte Kunststoffe weisen in der Herstellung im Vergleich zu alternativen Kunststoffen mit mehr als 70 MJ pro kg Kunststoff (71.2 MJ/kg bei PET) einen höheren Verbrauch an fossilen Ressourcen auf. Aber auch zwischen den alternativen Kunststoffen gibt es Unterschiede. Die Herstellung von PLA ist energieintensiver als die von PHA. Denn für die Produktion von PLA sind 57 MJ/kg erforderlich. Hingegen benötigt man für 1 kg PHA nur 45 MJ. Die Einsparung von fossilen Ressourcen in MJ/kg ist im Gegensatz zu konventionellen Kunststoffen bei der Produktion von PLA niedriger als bei der von PHA.</p>
<p>Der geringere Energiebedarf von PHA im Vergleich zu PLA führt zu einem geringeren Verbrauch an fossilen Brennstoffen, die eine wichtige Quelle für Treibhausgasemissionen sind. In Bezug auf die Auswirkungen auf das Klima wäre also eine Verwendung von PHA vorteilhaft. Der geringere Gesamtenergiebedarf könnte es eher möglich machen, diesen Energiebedarf durch erneuerbare Energiequellen zu decken. So kann letztendlich durch die Reduzierung der Treibhausgasemissionen der Klimawandel eingedämmt werden.</p>
</section>
<section id="treibhauspotential" class="level3">
<h3 class="anchored" data-anchor-id="treibhauspotential">Treibhauspotential</h3>
<p>Als Charakterisierungsfaktor für die globale Erwärmung wird die CO<sub>2</sub>-Äquivalente (CO<sub>2</sub>e) verwendet. Sie ist eine Größe zur Vereinheitlichung der Klimawirkung der unterschiedlichen Treibhausgase und ist in kg CO<sub>2</sub>e pro kg hergestellten Bio-Kunststoff angegeben. Kunststoffe, die aus fossilem Kohlenstoff bestehen, tragen zur Freisetzung von mehr klimawirksamen Treibhausgasen bei. Berechnungen haben ergeben, dass 241-316 Millionen Tonnen CO2-Äquivalent pro Jahr bei Verwendung von Biokunststoffen gespart werden können. So werden bei der Produktion von Biokunststoffen 80 % weniger CO<sub>2</sub> in die Atmosphäre abgegeben als bei der Erzeugung konventioneller Kunststoffe. Vergleicht man das Treibhauspotential zwischen PLA und PHA, so fällt dieses mit 3,8 kg CO<sub>2</sub>-Äquivalent pro kg Polymilchsäure höher aus als bei Polyhydroxyalkanoate mit ca. 3 kg CO<sub>2</sub>-Äquivalent pro kg des alternativen Kunststoffes. Somit spart PHA mehr Treibhausgasemissionen ein als PLA.</p>
<p>Bei der Betrachtung der Klimawirkung ist es wichtig, alle Phasen des Produktlebenszyklus zu berücksichtigen. Es sollte beachtet werden, dass bei biobasierten Kunststoffen das während des Pflanzenwachstums aufgenommene CO<sub>2</sub> in der Bilanz berücksichtigt wird, was zu einer Verbesserung des Treibhauspotenzials führt.</p>
<p>Die geringere CO<sub>2</sub>e bei der Produktion von PHA im Vergleich mit PLA geht mit einem niedrigeren Vorkommen von Treibhausgasen in der Atmosphäre einher, was den Treibhauseffekt und damit die globale Erwärmung reduziert. So kann es möglich sein, den Klimawandel und dessen negative Auswirkungen zu begrenzen und angestrebte Klimaziele zu erreichen.</p>
<!-- ### Quellen -->
<!-- -   [7 Plastik Alternativen aus der Forschung -->
<!--     CareElite](https://www.careelite.de/plastik-alternativen-forschung/#:~:text=Welche%20Plastik%20Alternativen%20aus%20der%20Forschung%20gibt%20es%3F,Hanf%20...%207%207.%20Plastik%20von%20Schalentieren%20) -->
<!-- -   [So lange braucht Abfall, um zu -->
<!--     verrotten](https://utopia.de/ratgeber/so-lange-braucht-abfall-um-zu-verrotten/) -->
<!-- -   [Plastikmüll und seine Folgen -->
<!--     NABU](https://www.nabu.de/natur-und-landschaft/meere/muellkippe-meer/muellkippemeer.html) -->
<!-- -   [Weichmacher in Plastik: So gesundheitsschädlich sind -->
<!--     Phthalate](https://www.aok.de/pk/magazin/nachhaltigkeit/muell-vermeiden/weichmacher-in-plastik-so-gesundheitsschaedlich-sind-phthalate/) -->
<!-- -   [Neue WWF-Studie zeigt die unglaublichen Kosten der Plastik-Krise - WWF -->
<!--     Österreich](https://www.wwf.at/neue-wwf-studie-zeigt-die-unglaublichen-kosten-der-plastik-krise/) -->
<!-- -   [Klimaneutral und schnell abbaubar: Bio-Kunststoff aus Cyanobakterien - -->
<!--     Forschung - -->
<!--     transgen.de](https://www.transgen.de/forschung/2808.bio-kunststoff-cyanobakterien.html) -->
<!-- -   https://www.spektrum.de/news/bakterien-erzeugen-biokunststoff/1015024 -->
<!-- -   [Biokunststoffe](https://link.springer.com/chapter/10.1007/978-3-658-27795-6_2) -->
<!-- -   [nova-Institut -->
<!--     (wip-kunststoffe.de)](https://wip-kunststoffe.de/fileadmin/user_upload/news_downloads/nova-Institut.pdf) -->
<!-- -   Durable Polylactic Acid (PLA)-Based Sustainable Engineered Blends and -->
<!--     Biocomposites: Recent Developments, Challenges, and Opportunities Neelima -->
<!--     Tripathi, Manjusri Misra, and Amar K. Mohanty ACS Engineering Au 2021 1 (1), -->
<!--     7-38 DOI: 10.1021/acsengineeringau.1c00011 -->
<!-- -   [Zuckerrohr-Verpackungen für die Umwelt -->
<!--     \|Verpacknachhaltig](https://verpacknachhaltig.de/zuckerrohr-verpackung/) -->
<!-- -   [Was ist Bagasse? Unsere Materialkunde zum nachhaltigen Verpackungsmaterial -->
<!--     -packVerde -->
<!--     (pack-verde.com)](https://www.pack-verde.com/blog/at/materialkunde/materialkunde-bagasse/) -->
<!-- -   [Bagasse: Plastikalternative aus Zuckerrohr -->
<!--     -Utopia.de](https://utopia.de/ratgeber/bagasse-plastikalternative-aus-zuckerrohr/) -->
<!-- -   [Was sind die Vor- und Nachteile von Bagasse? - Nachricht -->
<!--     (zc-pak.com)](https://de.zc-pak.com/news/what-is-bagasse-advantages-and-disadvantages-66845834.html#:~:text=Nachteile%20von%20Bagasse%3A%201%201.%20Nicht%20wasserfest%3A%20Bagasse,um%20in%20brauchbare%20Produkte%20umgewandelt%20zu%20werden.%20) -->
<!-- -   [Einweggeschirr: Wie nachhaltig sind Plastikalternativen? - -->
<!--     Utopia.de](https://utopia.de/ratgeber/einweggeschirr-wie-nachhaltig-sind-die-alternativen-zu-plastik/) -->
<!-- -   <https://utopia.de/news/verbraucherzentralen-warnen-bambusgeschirr-plastik/> -->
<!-- -   [Wie nachhaltig ist der Kunststoff? - -->
<!--     Utopia.de](https://utopia.de/ratgeber/pla-wie-nachhaltig-ist-der-kunststoff/#:~:text=Das%20Umweltbundesamt%20best%C3%A4tigt%2C%20dass%20PLA-Kunststoff%20biologisch%20abbaubar%20ist.,zu%20Folie%20verarbeiten%20und%20ist%20fest%20und%20stabil.) -->
<!-- -   [Wie nachhaltig ist PLA Filament wirklich? -->
<!--     -3Dnatives](https://www.3dnatives.com/de/feature-story-3d-druck-material-pla-nachhaltig-230720191/) -->
<!-- -   [Polylactid (PLA) -->
<!--     --Biokunststofftool](https://biokunststofftool.de/werkstoffe/pla-polylactid/#Werkstoffhersteller) -->
<!-- -   Al-Khairy D, Fu W, Alzahmi AS, Twizere JC, Amin SA, Salehi-Ashtiani K, -->
<!--     Mystikou A. Closing the Gap between Bio-Based and Petroleum-Based Plastic -->
<!--     through Bioengineering. Microorganisms. 2022 Nov 23;10(12):2320. doi: -->
<!--     10.3390/microorganisms10122320. PMID: 36557574; PMCID: PMC9787566. -->
<!-- -   [Polymilchsäure](https://link.springer.com/chapter/10.1007/978-3-662-64469-0_35) -->
<!-- -   [Biopolymers-Facts-Statistics-2020](https://www.ifbb-hannover.de/files/IfBB/downloads/faltblaetter_broschueren/f+s/Biopolymers-Facts-Statistics-2020.pdf) -->
<!-- -   [Biokunststoffe - -->
<!--     FraunhoferINT](https://www.int.fraunhofer.de/de/geschaeftsfelder/corporate-technology-foresight/trend-news/biokunststoffe.html) -->
<!-- -   [https://de.statista.com/](https://de.statista.com/statistik/daten/studie/206250/umfrage/landwirtschaftliche-nutzflaeche-in-deutschland/#:~:text=2023%20lag%20die%20landwirtschaftliche%20Nutzfl%C3%A4che%20in%20Deutschland%20bei,dem%20Vorjahr%20blieb%20die%20Agrarfl%C3%A4che%20somit%20nahezu%20konstant). -->
<!-- -   Tanadchangsaeng N, Pattanasupong A. Evaluation of Biodegradabilities of -->
<!--     Biosynthetic Polyhydroxyalkanoates in Thailand Seawater and Toxicity -->
<!--     Assessment of Environmental Safety Levels. Polymers (Basel). 2022 Jan -->
<!--     21;14(3):428. doi: 10.3390/polym14030428. PMID: 35160420; PMCID: PMC8840047. -->
<!-- -   Bioplastic: An Eco‐friendly Alternative of Non‐Biodegradable Plastic June -->
<!--     2023 DOI:10.1002/pi.6555 -->
<!-- -   Serrano-Aguirre L, Prieto MA. Can bioplastics always offer a truly -->
<!--     sustainable alternative to fossil-based plastics? Microb Biotechnol. 2024 -->
<!--     Apr;17(4):e14458. doi: 10.1111/1751-7915.14458. PMID: 38568795; PMCID: -->
<!--     PMC10990045. -->
<!-- -   [Review of recent advances in the biodegradability of polyhydroxyalkanoate -->
<!--     (PHA) bioplastics and their composites - Green Chemistry (RSC -->
<!--     Publishing)](https://pubs.rsc.org/en/content/articlelanding/2020/gc/d0gc01647k#:~:text=PHAs%20such%20as%20poly%20%283-hydroxybutyrate%29%20%28PHB%29%20and%20poly,the%20negativity%20associated%20with%20the%20landfilling%20of%20plastics.) -->
<!-- -   Piemonte, Vincenzo. (2011). 1. V. Piemonte, F. Gironi. Bioplastics and -->
<!--     Petroleum-based Plastics: Strengths and Weaknesses, Energy Sources Part A: -->
<!--     Energy, recovery and Environmental Effect, 2011, 33, 1949-1959. (DOI: -->
<!--     10.1080/15567030903436830). Energy Sources Part A Recovery Utilization and -->
<!--     Environmental Effects. -->
<!-- -   [PET, PE und PVC: Das müssen Sie über Kunststoffe wissen \| -->
<!--     Verbraucherzentrale.de](https://www.verbraucherzentrale.de/wissen/lebensmittel/lebensmittelproduktion/kunststoffe-7035) -->
<!-- -   [Polyethylenterephthalat -->
<!--     (chemie.de)](https://www.chemie.de/lexikon/Polyethylenterephthalat.html) -->
<!-- -   Soong, Y.-H.V.; Sobkowicz, M.J.; Xie, D. Recent Advances in Biological -->
<!--     Recycling of Polyethylene Terephthalate (PET) Plastic Wastes. Bioengineering -->
<!--     2022, 9, 98. https://doi.org/10.3390/bioengineering9030098 -->
<!-- -   ["Nein zur Wegwerfgesellschaft" -- 5-Punkte-Plan des -->
<!--     Bundesumweltministeriums für weniger Plastik und mehr -->
<!--     Recycling(bmuv.de)](https://www.bmuv.de/fileadmin/Daten_BMU/Download_PDF/Abfallwirtschaft/181123_5_punkte_plan_plastik_bf.pdf) -->
<!-- -   [Plastikmüll Statistiken in Deutschland, weltweit und im Meer -->
<!--     (2023)(aktivbewusst.de)](https://aktivbewusst.de/plastikmuell-statistiken-deutschland-weltweit/#t-1691126514865) -->
<!-- -   [So werden Plastikflaschen wiederverwertet -->
<!--     -quarks.de](https://www.quarks.de/umwelt/muell/so-werden-plastikflaschen-wiederverwertet/) -->
<!-- -   [EU packaging waste generation with record increase - Eurostat -->
<!--     (europa.eu)](https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20231019-1) -->
<!-- -   [Plastikatlas 2019 -->
<!--     (boell.de)](https://www.boell.de/sites/default/files/2019-11/Plastikatlas_2019_3._Auflage.pdf) -->
<!-- -   171025-nabu-01b_studie_verwendung-und-recycling-pet-deutschland.pdf(https://www.nabu.de/imperia/md/content/nabude/veranstaltungen/171025-nabu-01b_studie_verwendung-und-recycling-pet-deutschland.pdf) -->
<!-- -   [Landwirtschaftszählung 2020 - Statistisches Bundesamt -->
<!--     (destatis.de)](https://www.destatis.de/DE/Themen/Branchen-Unternehmen/Landwirtschaft-Forstwirtschaft-Fischerei/Landwirtschaftszaehlung2020/_inhalt.html) -->
<!-- -   [PET: Produktion in Deutschland bis 2023 \| -->
<!--     Statista](https://de.statista.com/statistik/daten/studie/1285091/umfrage/polyethylenterephthalat-produktion-in-deutschland/#:~:text=Im%20Jahr%202023%20wurden%20in%20Deutschland%20seitens%20der,vorwiegend%20bei%20der%20Produktion%20von%20Kunststoffflaschen%20verwendet%20wird.) -->
<!-- -   [PET global production 2020 -->
<!--     \|Statista](https://www.statista.com/statistics/650191/global-polyethylene-terephthalate-production-outlook/) -->
<!-- -   https://www.umweltbundesamt.de/biobasierte-biologisch-abbaubare-kunststoffe#310-bieten-verpackungen-aus-biologisch-abbaubaren-kunststoffen-vorteile -->
<!-- -   [Material_choices_211020.pdf -->
<!--     (greentechknowledgehub.de)](https://greentechknowledgehub.de/sites/default/files/2021-10/Material_choices_211020.pdf) -->
<!-- -   Energy Inputs on the Production of Plastic Products September 2022Journal of -->
<!--     Ecological Engineering 23(9):146-156 23(9):146-156 -->
<!--     DOI:10.12911/22998993/151815 -->
<!-- -   [Effiziente Biokunststoff Herstellung mit Industriezentrifugen -->
<!--     (flottweg.com)](https://www.flottweg.com/de/anwendungen/pharmazie-und-biotechnologie/biokunststoff/) -->
</section>
</section>
<section id="pet-und-alternativen" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="pet-und-alternativen"><span class="header-section-number">5.2</span> PET und Alternativen</h2>
<section id="aufgabenstellung-1" class="level3">
<h3 class="anchored" data-anchor-id="aufgabenstellung-1">Aufgabenstellung</h3>
<p>Die Produktion von Kunststoffen hat in den letzten Jahrzehnten stark zugenommen und ist von 1,7 Millionen Tonnen im Jahr 1950 auf 367 Millionen Tonnen im Jahr 2020 gestiegen. Ein Teil des Plastikmülls gelangt in die Umwelt und führt dazu, dass jährlich über 1 Millionen Meeresbewohner verenden. Im Jahr 2021 produzierten Einwohner in Deutschland pro Person ca. 41 kg Verpackungsmüll aus Kunststoff. Viele Verpackungen bestehen aus Polyethylenterephthalat (PET). Plastik ist in der Natur nicht vollständig abbaubar, sondern zersetzt sich in immer kleinere Partikel. Das entstandene Mikroplastik kann über Gewässer in die Nahrungskette gelangen und der Mensch nimmt es z. B. durch den Verzehr von Fisch auf. Im Mittel nimmt jeder Mensch laut einer Studie pro Woche 5 Gramm Mikroplastik - das ist ungefähr das Gewicht einer Kreditkarte - auf.</p>
<p>Die Entwicklung und der Einsatz von nachhaltigen Plastik-Alternativen werden also immer ausschlaggebender. Aktuell wird darüber diskutiert, welcher biobasierter Kunststoff gefördert werden soll.</p>
<p>Konkret wird beraten, ob</p>
<ol type="a">
<li>Polymilchsäure (PLA) oder</li>
<li>Polyhydroxyalkanoate (PHA)</li>
<li>Polyethylenterephthalat (PET)</li>
</ol>
<p>verstärkt gefördert werden soll.</p>
<p>Diskutieren Sie die vorgeschlagenen Kunststoffe vor dem Hintergrund der Nachhaltigkeit auf der Basis von mindestens drei Kriterien aus den Materialien der folgenden Seiten. Stärken Sie Ihre Argumente, indem Sie die Relevanz der Kriterien für Ihre Behauptungen erklären.</p>
<p><strong>Begrifflichkeiten</strong></p>
<p>Im Allgemeinen werden Biokunststoffe aus erneuerbaren Ressourcen hergestellt und es werden keine fossilen Brennstoffe verwendet. Konventionelles Plastik wird aus Rohöl hergestellt, was eine begrenzte Ressource ist. Kunststoff-Alternativen können verwendet werden, um Umweltproblemen entgegenzuwirken, welche beispielsweise durch die unsachgemäße Entsorgung von Plastikmüll entstehen. Im Gegensatz zu konventionellen Kunststoffen können Biokunststoffe zersetzt werden und die Einleitung von schädlichen Chemikalien in die Natur kann reduziert werden.</p>
<p>Bei der Verwendung des Begriffs Biokunststoff ist zu beachten, dass er Materialien umfasst, die entweder aus nachwachsenden Rohstoffen (Biomasse) hergestellt werden, kompostierbar/biologisch abbaubar sind oder beide Eigenschaften besitzen.</p>
<p>Laut Definition kann ein biobasiertes/biogenes Produkt vollständig oder teilweise aus Biomasse bestehen. Das heißt, dass Mischstoffe aus biobasierten und auch erdölbasierten Kunststoffen unter diesen Begriff fallen. Hier wird davon ausgegangen, dass die biobasierten Kunststoffe zu 100 % aus pflanzlichen Rohstoffen produziert wurden.</p>
<p><strong>Polymilchsäure</strong></p>
<p>PLA ist ein Polyester, das aus nachwachsenden und natürlichen Rohstoffen hergestellt wird und industriell kompostiert werden kann. Es zählt zu den meist eingesetzten und vielversprechendsten Materialien für Kunststoff-Alternativen. Als Ausgangsmaterialien werden stärkereiche landwirtschaftliche Nebenprodukte und Produkte verwendet. Polymilchsäure wird produziert, indem Stärke extrahiert wird und mit Hilfe von Enzymen in Glucose umgewandelt wird. Mikroorganismen fermentieren Glucosee in Milchsäure, die dann in Polylactid umgewandelt werden. PLA kann also durch Polykondensation von Milchsäure oder durch Polymerisation hergestellt werden.</p>
<p><strong>Polyhydroxyalkanoate</strong></p>
<p>Polyhydroxyalkanoate sind Polyester, die ebenfalls aus natürlichen Rohstoffen hergestellt werden. Dies geschieht durch die Fermentation von Zuckern und Lipiden. Die Biopolymere werden von verschiedenen Mikroorganismen produziert und dienen ihnen als Speicherstoffe. Nachdem die Mikroorganismen im Nährmedium kultiviert wurden und eine bestimmte Zelldichte erreicht haben, werden Mangelbedingungen und ein Überschuss an Kohlenstoff eingestellt. Dadurch werden die Biopolyester im Cytoplasma synthetisiert und in Form von Körnchen (Granula) in den Zellen akkumuliert.</p>
<p>Auch PHA wird weit verbreitet eingesetzt und scheint aussichtsreich zu sein. Polyhydroxybutyrat (PHB) ist der bekannteste Vertreter innerhalb der PHA Familie.</p>
<p><strong>Polyethylenterephthalat</strong></p>
<p>Polyethylenterephthalat ist aus einer Kette von Monomeren des Ethylenterephthalats aufgebaut. Dies besteht aus den Komponenten Terephthalsäure und Ethylenglykol, die miteinander verestert sind. Anschließend erfolgt die Polykondensation unter Abspaltung von Wasser. Es entsteht ein zähflüssiges Material, welches weiterverarbeitet werden kann. Es wird z. B. in Fäden gepresst oder Granulat hergestellt. Die verwendeten Stoffe werden aus Rohöl gewonnen. PET wird also nicht aus erneuerbaren Ressourcen hergestellt, da es aus fossilen Kohlenwasserstoffen aufgebaut wird.</p>
<p>Es weist eine hohe Festigkeit auf und ist beständig gegen Feuchtigkeit, verdünnte Säuren, Öle, Fette und Alkohole. Der Kunststoff wird hauptsächlich für Getränkeflaschen, dünne Folien und Lebensmittelbehälter und Verpackungen verwendet. Auch als Textilfaser/Polyester wird PET in der Bekleidungsindustrie häufig eingesetzt, da es witterungsbeständig ist und wenig Wasser aufnimmt.</p>
<p>Allein in Deutschland wurden 314.500 Tonnen Polyethylenterephthalat im Jahr 2023 hergestellt. Im Vergleich zum Vorjahr ist die Produktion mit 515.171 t somit zurückgegangen. Weltweit im Jahr 2020 betrug die PET-Produktion ungefähr 73.39 Millionen Tonnen.</p>
</section>
<section id="kriterienüberischt" class="level3">
<h3 class="anchored" data-anchor-id="kriterienüberischt">Kriterienüberischt</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Kriterium</strong></td>
<td style="text-align: left;"><strong>Polymilchsäure (PLA)</strong></td>
<td style="text-align: left;"><strong>Poly hydroxyalkanoate (PHA)</strong></td>
<td style="text-align: left;"><strong>Polyeth ylenterephthalat (PET)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Menge benötigter Rohstoffe</td>
<td style="text-align: left;">2,39 t bis 11,31 t pro 1 t PLA</td>
<td style="text-align: left;">4,63 t bis 22 t pro 1 t PHB</td>
<td style="text-align: left;">2 t Rohöl (fossiler Herkunft) pro 1 t PET</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flächenbedarf der Rohstoffe</td>
<td style="text-align: left;">0,16 ha bis 1,04 ha pro 1 t PLA</td>
<td style="text-align: left;">0.30 ha bis 1.88 ha pro 1 t PHB</td>
<td style="text-align: left;">11,74 bis 22,02 Mio. ha um die gesamte Produktion von PET durch PLA oder PHA zu ersetzen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wasserbedarf der Rohstoffe</td>
<td style="text-align: left;">1215 m<sup>3</sup> bis 6 468 m<sup>3</sup> pro 1 t PLA</td>
<td style="text-align: left;">2364 m<sup>3</sup> bis 12867 m<sup>3</sup> pro 1 t PHB</td>
<td style="text-align: left;">294,2 m<sup>3</sup> pro t PET</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alternative Herstellung</td>
<td style="text-align: left;">in genetisch veränderte <em>Escherichia coli</em></td>
<td style="text-align: left;">PHB in Cyanobakterien</td>
<td style="text-align: left;">“Bio PET 30” teilweise aus nachwachsenden Rohstoffen</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biologische Abbaubarkeit</td>
<td style="text-align: left;"><p>Temperatur: 58 °C</p>
<p>Abbaubarkeit: 85 – 90 %</p>
<p>Dauer: 65 Tage</p></td>
<td style="text-align: left;"><p>Temperatur: 30 – 35 °C</p>
<p>Abbaubarkeit: 20 – 28 %</p>
<p>Dauer: 28 Tage</p></td>
<td style="text-align: left;"><p>nicht biologisch abbaubar, zersetzt sich in Mikroplastik,</p>
<p>dauert bis zu 450 Jahre</p></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Energiebedarf</td>
<td style="text-align: left;">57 MJ/kg</td>
<td style="text-align: left;">45 MJ/kg</td>
<td style="text-align: left;">71.2 MJ/kg</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treib- hauspotential</td>
<td style="text-align: left;">3,8 kg CO<sub>2</sub>e pro kg PLA</td>
<td style="text-align: left;">3 kg CO<sub>2</sub>e pro kg PHA</td>
<td style="text-align: left;">bis zu 5 mal soviel</td>
</tr>
</tbody>
</table>
</section>
<section id="verwendete-rohstoffe-1" class="level3">
<h3 class="anchored" data-anchor-id="verwendete-rohstoffe-1">Verwendete Rohstoffe</h3>
<p>Zur Herstellung von PLA können unterschiedliche Kohlenhydratquellen als Ausgangsstoffe verwendet werden. So kann neben Pflanzenöl der Zucker aus Zuckerrohr oder Zuckerrüben oder Stärke aus z. B. Mais oder Weizen verwendet werden.</p>
<p>Die Menge an benötigtem Rohstoff ist mit 2,39 t Mais am geringsten und mit 11,31 t Zuckerrohr am höchsten um 1 t PLA herzustellen. Vergleicht man diese Werte mit den notwendigen Mengen der gleichen Rohstoffe für die Herstellung von 1 t PHB, fallen diese geringer aus. Für die Herstellung von PHB wird also etwas mehr Rohstoff gebraucht. Für 1 t PHB werden beispielsweise 4,63 t Mais und 22 t vom Zuckerrohr eingesetzt. Dennoch bestimmt der verwendete, am jeweils besten geeignete Rohstoff, ob für die PLA- oder PHB-Produktion letztlich verwendet wird. Bei der Herstellung von Zucker entstehen beim Auspressen von Zuckerrohr faserige Überreste. Diese gemahlenen Fasern werden weiterverarbeitet. Zuckerrohr ist ein schnell nachwachsender Rohstoff, der sowohl kälte- als auch hitzebeständig sowie geschmacksneutral ist. Diese faserigen Überreste bilden die Grundlage für verschiedene biobasierte Kunststoffe. Produkte, die aus diesen Resten hergestellt werden, sind daher nachhaltig und der Ertrag ist hoch, weil aus 100 Tonnen Zuckerrohr mehr als dreimal so viel faseriges Material gewonnen werden kann wie Zucker.</p>
<p>Die Vielfalt der Ausgangsstoffe ermöglicht eine flexible und anpassungsfähige Produktion, je nach den lokalen Bedingungen. Dennoch ist es wichtig, möglichst wenig Rohstoffe zu verwenden, damit diese nicht an anderer Stelle wie in der Lebensmittelbranche oder im Futtermittelsektor fehlen. Um der Belastung der Anbauflächen entgegenzuwirken und die Umwelt zu schonen, ist die Verwendung von Reststoffen empfehlenswert.</p>
<p>Im Vergleich dazu werden bei der Herstellung von PET fossiler Herkunft, Ethylenglycol und Terephthalsäure aus Rohöl gewonnen. Für die Herstellung von einer Tonne PET werden fast 2 t Öl- und Gasressourcen benötigt. Hierbei wird sowohl die Verwendung fossiler Brennstoffe als Rohstoff und auch als Energiequelle während des Produktionsprozesses berücksichtigt.</p>
</section>
<section id="flächenbedarf-der-rohstoffe-1" class="level3">
<h3 class="anchored" data-anchor-id="flächenbedarf-der-rohstoffe-1">Flächenbedarf der Rohstoffe</h3>
<p>Die benötigte Fläche für Rohstoffe, welche für eine Tonne PLA benötigt werden, unterscheidet sich leicht von der Fläche, die für eine Tonne PHB beansprucht wird. Der Flächenbedarf wird in Hektar (ha) angegeben. Um 1 t PLA zu produzieren, wird 0,16 ha (Zuckerrohr) bis 1,04 ha (Weizen) Fläche benötigt, um die erforderliche Menge des jeweiligen Rohstoffes anzubauen. Hingegen wird für die Herstellung von PHB eine Fläche von 0.30 ha (Zuckerrohr) bis 1.88 ha (Weizen) benötigt.</p>
<p>Die landwirtschaftliche Nutzfläche in der Europäischen Union beträgt ca. 174 Millionen ha. Im Vergleich dazu würden z. B. die zur Zeit erzeugten 100.000 t PLA-Fasern mit 16.000 ha (Zuckerrohr) bis 100.000 ha (Weizen) eine geringe Fläche einnehmen.</p>
<p>Im Mittel nimmt die Produktion von PLA im Vergleich zu PHA weniger Fläche in Anspruch. Somit können auch der Verlust der biologischen Vielfalt und die Belastung der Böden geringer ausfallen. Es ist wichtig zu beachten, dass durch die Herstellung von Biokunststoffen eine Konkurrenz zwischen Anbauflächen für Rohstoffe für Alternative-Kunststoffe und Anbauflächen für Nahrungsmittel entstehen könnte. Die Verwendung von Reststoffen könnte diesem Problem aber entgegenwirken. Es könnte umweltschonend und nachhaltig gewirtschaftet werden, wenn nur Reste von Rohstoffen eingesetzt werden, die ansonsten verbrannt werden würden.</p>
<p>Es würden etwa 11,74 Millionen Hektar landwirtschaftliche Fläche benötigt, um die gesamte weltweite PET-Produktion von 73,39 Millionen Tonnen durch PLA zu ersetzen, wenn als Rohstoff Zuckerrohr eingesetzt werden würde. Würde die gesamte PET-Produktion durch PHB ersetzt werden, dann wären ca. 22,02 Millionen Hektar landwirtschaftliche Fläche für den Anbau des Rohstoffs (Zuckerrohr) notwendig. Im Vergleich dazu betrug die gesamte landwirtschaftlich genutzte Fläche in Deutschland im Jahr 2020 16,6 Millionen Hektar.</p>
</section>
<section id="wasserbedarf-der-rohstoffe-1" class="level3">
<h3 class="anchored" data-anchor-id="wasserbedarf-der-rohstoffe-1">Wasserbedarf der Rohstoffe</h3>
<p>Auch die benötigte Menge an Wasser, die für die Herstellung der Rohstoffe benötigt wird, unterscheidet sich zwischen Polymilchsäure und Polyhydroxybutyrat. Der Wasserverbrauch wird in Kubikmetern angegeben. Für die Herstellung von einer Tonne PLA sind 1215 m<sup>3</sup> (Zuckerrübe) bis 6468 m<sup>3</sup> (Weizen) Wasser notwendig. Hingegen werden 2364 m<sup>3</sup> (Zuckerrübe) bis 12867 m<sup>3</sup> (Weizen) Wasser verwendet, um die Rohstoffe für die gleiche Menge PHB zu produzieren.</p>
<p>Diese große Menge an Wasser kann durch eine alternative Produktion von PHB durch Cyanobakterien vermieden werden. Die Cyanobakterien benötigen keine intensive Bewässerung, wie der Anbau der Rohstoffe zur Produktion von PLA und PHA/PHB. So können Cyanobakterien in Abwassern wachsen und anfallender Stickstoff und Phosphat können zur Kultivierung genutzt werden. Auf diese Weise kann eine beträchtliche Menge an Süßwasser gespart werden. Diese Art der Herstellung von PHB verringert den Druck auf Gewässer, da keine landwirtschaftlichen Flächen benötigt werden, auf denen Pestizide eingesetzt werden, die anschließend ins Grundwasser gelangen. Zudem trägt dieser Ansatz zu einer effektiven Kreislaufwirtschaft bei, da die vorhandenen Nährstoffe im Abwasser genutzt werden. Indirekt kann durch diese Produktionsweise auch zum Klimaschutz beigetragen werden, da weniger kohlenstoffspeichernde Ökosysteme (z. B. Regenwälder) gerodet werden müssen.</p>
<p>Im Gegensatz zu der Produktion der alternativen Kunststoffe aus landwirtschaftlichen Rohstoffen ist die Herstellung von PET mit einer Menge von 294,2 m<sup>3</sup> Wasser pro Tonne PET vergleichsweise gering.</p>
</section>
<section id="alternative-produktion-1" class="level3">
<h3 class="anchored" data-anchor-id="alternative-produktion-1">Alternative Produktion</h3>
<p>Zudem besteht die Möglichkeit, auf die zuvor genannten Rohstoffe zu verzichten und durch den Einsatz von Bakterien Biokunststoff zu produzieren. <em>Escherichia coli</em> (<em>E. coli</em>) Bakterien können PLA direkt aus Traubenzucker herstellen. Dafür müssen die Organismen allerdings genetisch verändert werden. Zudem ist die Konzentration des erzeugten PLAs noch zu gering für eine industrielle Anwendung. Auch PHB kann in Bioreaktoren durch heterotrophe Bakterien wie <em>Cupriavidus necator</em> und ebenfalls durch genetisch veränderte <em>E. coli</em> hergestellt werden. Hier ist allerdings der Nachteil, dass für die Fermentationsprozesse immer noch viel organischer Kohlenstoff (z. B. Glucose) notwendig ist. Alternativ besteht die Möglichkeit, Cyanobakterien unter Nährstoffmangel für die Herstellung kleiner Mengen von PHB einzusetzen. Sie können durch die Fotosynthese Licht als Energie nutzen und dabei CO<sub>2</sub> (Kohlenstoffdioxid) binden. So kann PHB auf eine nachhaltige Weise produziert werden und Flächen und Rohstoffe gespart werden. Dadurch wird die Umwelt geschont und auch die Effizienz kann durch die Produktion unter kontrollierten Bedingungen in Bioreaktoren gesteigert werden. Die dezentrale Einsetzbarkeit von Bioreaktoren reduziert die Transportwege. Obwohl diese Art der Produktion planbarer und stabiler ist als die Nutzung landwirtschaftlicher Rohstoffe, ist die Herstellung von genetisch veränderten Organismen zeitaufwendig und kostenintensiv.</p>
<p>Es ist theoretisch auch möglich, die beiden notwendigen Grundbausteine von PET aus nachwachsenden Rohstoffen zu gewinnen. Zurzeit kann aber nur Ethylenglycol erworben werden, welches aus biobasierten Materialien gewonnen wurde. Dieses wird aus dem Rohstoff Zuckerrohr gewonnen. In dem entstehenden Polyethylenterephthalat, welches unter dem Namen “Bio PET 30” gehandelt wird, stammen 30 % der Kohlenstoffatome ursprünglich von nachwachsenden Rohstoffen. Hingegen ist der Gewinn von Terephthalsäure aus Biomasse momentan Forschungsgegenstand und somit eine großtechnische Produktion noch nicht möglich.</p>
</section>
<section id="biologische-abbaubarkeit-1" class="level3">
<h3 class="anchored" data-anchor-id="biologische-abbaubarkeit-1">Biologische Abbaubarkeit</h3>
<p>Biologische Abbaubarkeit bedeutet, dass ein Stoff in CO<sub>2</sub>, CH<sub>4</sub> (Methan), Wasser, Biomasse und anorganische Verbindungen zersetzt werden kann. Für einen erfolgreichen Abbau müssen aber bestimmte Bedingungen vorherrschen, wie beispielsweise höhere Temperaturen, auch können Enzyme oder Mikroorganismen hinzugefügt werden. Es bedeutet also nicht, dass diese Materialien natürlich abbaubar sind und auf dem heimischen Kompost verrotten können.</p>
<p>PLA lässt sich bei Temperaturen von ca. 58 °C und einer hohen Luftfeuchtigkeit von über 98 % biologisch abbaubar. Die Polymilchsäure wird durch Hydrolyse gespalten und anschließend durch Mikroorganismen zersetzt. Die biologische Abbaubarkeit beträgt 85-90 % innerhalb von ungefähr 65 Tagen. Im Meerwasser kann PLA fast nicht abgebaut werden und es wurden bereits durch PLA-Mikropartikel ausgelöste Stoffwechselveränderungen bei Miesmuscheln nachgewiesen. Hingegen können verschiedene PHAs in 28 Tagen beispielsweise zu 61 % (PHB) zersetzt werden. Zudem wurde nach Abbau keine Toxizität festgestellt und Testorganismen waren zu 100 % lebensfähig. Auch die Kompostiertemperatur von PHA hingegen ist mit Temperaturen 30-35 °C geringer. Ungefähr 20 bis 28 % können in 28 Tagen zersetzt werden.</p>
<p>Eine schnelle Abbaubarkeit ist wichtig, da das Vorkommen in der Umwelt Tiere und Pflanzen belastet. Je schneller ein Material abgebaut wird, desto geringer ist die Wahrscheinlichkeit, dass es zu Mikroplastik zerfällt und in Nahrungsketten gelangt. Die Abbaubarkeit in natürlichen Umgebungen von PHB und vor allem PLA ist aber deutlich eingeschränkt. Die hohen benötigten Temperaturen für den Abbau in der Kompostieranlage verbrauchen Energie und könnten bei Nutzung nicht erneuerbarer Energiequellen den Klimawandel fördern. Da die erforderliche Temperatur für den Abbau von PLA höher ist, ist es wahrscheinlich, dass sich dessen Verwendung schädlicher auf das Klima auswirkt.</p>
<p>Hingegen ist PET nicht biologisch abbaubar und eine Plastikflasche benötigt ca. 450 Jahre, bis sie sich im Wasser zersetzt und in Fokm von Mikroplastik auf den Meeresgrund sinkt. Eine Einkaufstüte benötigt 10 bis 20 Jahre, bis sie sich zersetzt. Aufgrund der langen Zeit des Abbaus ist ein effektives Recycling von größter Bedeutung.</p>
</section>
<section id="energiebedarf-1" class="level3">
<h3 class="anchored" data-anchor-id="energiebedarf-1">Energiebedarf</h3>
<p>Ein anderer wichtiger Faktor, um die Umweltauswirkungen besser einschätzen zu können, ist der Energiebedarf. Angegeben ist der Bedarf an Energie aus nicht erneuerbaren Quellen, welcher notwendig ist, um 1 kg des jeweiligen biobasierten Kunststoffes herzustellen. Der Energiebedarf wird in Megajoule (MJ) angegeben. Erdölbasierte Kunststoffe weisen in der Herstellung im Vergleich zu alternativen Kunststoffen mit mehr als 70 MJ pro kg Kunststoff (71.2 MJ/kg bei PET) einen höheren Verbrauch an fossilen Ressourcen auf. Aber auch zwischen den alternativen Kunststoffen gibt es Unterschiede. Die Herstellung von PLA ist energieintensiver als die von PHA. Denn für die Produktion von PLA sind 57 MJ/kg erforderlich. Hingegen benötigt man für 1 kg PHA nur 45 MJ. Die Einsparung von fossilen Ressourcen in MJ/kg ist im Gegensatz zu konventionellen Kunststoffen bei der Produktion von PLA niedriger als bei der von PHA.</p>
<p>Der geringere Energiebedarf von PHA im Vergleich zu PLA führt zu einem geringeren Verbrauch an fossilen Brennstoffen, die eine wichtige Quelle für Treibhausgasemissionen sind. In Bezug auf die Auswirkungen auf das Klima wäre also eine Verwendung von PHA vorteilhaft. Der geringere Gesamtenergiebedarf könnte es eher möglich machen, diesen Energiebedarf durch erneuerbare Energiequellen zu decken. So kann letztendlich durch die Reduzierung der Treibhausgasemissionen der Klimawandel eingedämmt werden.</p>
</section>
<section id="treibhauspotential-1" class="level3">
<h3 class="anchored" data-anchor-id="treibhauspotential-1">Treibhauspotential</h3>
<p>Als Charakterisierungsfaktor für die globale Erwärmung wird die CO<sub>2</sub>-Äquivalente (CO<sub>2</sub>e) verwendet. Sie ist eine Größe zur Vereinheitlichung der Klimawirkung der unterschiedlichen Treibhausgase und ist in kg CO<sub>2</sub>e pro kg hergestellten Bio-Kunststoff angegeben. Kunststoffe, die aus fossilem Kohlenstoff bestehen, tragen zur Freisetzung von mehr klimawirksamen Treibhausgasen bei. Berechnungen haben ergeben, dass 241-316 Millionen Tonnen CO2-Äquivalent pro Jahr bei Verwendung von Biokunststoffen gespart werden können. So werden bei der Produktion von Biokunststoffen 80 % weniger CO<sub>2</sub> in die Atmosphäre abgegeben als bei der Erzeugung konventioneller Kunststoffe. Vergleicht man das Treibhauspotential zwischen PLA und PHA, so fällt dieses mit 3,8 kg CO<sub>2</sub>-Äquivalent pro kg Polymilchsäure höher aus als bei Polyhydroxyalkanoate mit ca. 3 kg CO<sub>2</sub>-Äquivalent pro kg des alternativen Kunststoffes. Somit spart PHA mehr Treibhausgasemissionen ein als PLA.</p>
<p>Bei der Betrachtung der Klimawirkung ist es wichtig, alle Phasen des Produktlebenszyklus zu berücksichtigen. Es sollte beachtet werden, dass bei biobasierten Kunststoffen das während des Pflanzenwachstums aufgenommene CO<sub>2</sub> in der Bilanz berücksichtigt wird, was zu einer Verbesserung des Treibhauspotenzials führt.</p>
<p>Die geringere CO<sub>2</sub>e bei der Produktion von PHA im Vergleich mit PLA geht mit einem niedrigeren Vorkommen von Treibhausgasen in der Atmosphäre einher, was den Treibhauseffekt und damit die globale Erwärmung reduziert. So kann es möglich sein, den Klimawandel und dessen negative Auswirkungen zu begrenzen und angestrebte Klimaziele zu erreichen.</p>
<!-- ### Quellen -->
<!-- -   [7 Plastik Alternativen aus der Forschung -->
<!--     CareElite](https://www.careelite.de/plastik-alternativen-forschung/#:~:text=Welche%20Plastik%20Alternativen%20aus%20der%20Forschung%20gibt%20es%3F,Hanf%20...%207%207.%20Plastik%20von%20Schalentieren%20) -->
<!-- -   [So lange braucht Abfall, um zu -->
<!--     verrotten](https://utopia.de/ratgeber/so-lange-braucht-abfall-um-zu-verrotten/) -->
<!-- -   [Plastikmüll und seine Folgen -->
<!--     NABU](https://www.nabu.de/natur-und-landschaft/meere/muellkippe-meer/muellkippemeer.html) -->
<!-- -   [Weichmacher in Plastik: So gesundheitsschädlich sind -->
<!--     Phthalate](https://www.aok.de/pk/magazin/nachhaltigkeit/muell-vermeiden/weichmacher-in-plastik-so-gesundheitsschaedlich-sind-phthalate/) -->
<!-- -   [Neue WWF-Studie zeigt die unglaublichen Kosten der Plastik-Krise - WWF -->
<!--     Österreich](https://www.wwf.at/neue-wwf-studie-zeigt-die-unglaublichen-kosten-der-plastik-krise/) -->
<!-- -   [Klimaneutral und schnell abbaubar: Bio-Kunststoff aus Cyanobakterien - -->
<!--     Forschung - -->
<!--     transgen.de](https://www.transgen.de/forschung/2808.bio-kunststoff-cyanobakterien.html) -->
<!-- -   https://www.spektrum.de/news/bakterien-erzeugen-biokunststoff/1015024 -->
<!-- -   [Biokunststoffe](https://link.springer.com/chapter/10.1007/978-3-658-27795-6_2) -->
<!-- -   [nova-Institut -->
<!--     (wip-kunststoffe.de)](https://wip-kunststoffe.de/fileadmin/user_upload/news_downloads/nova-Institut.pdf) -->
<!-- -   Durable Polylactic Acid (PLA)-Based Sustainable Engineered Blends and -->
<!--     Biocomposites: Recent Developments, Challenges, and Opportunities Neelima -->
<!--     Tripathi, Manjusri Misra, and Amar K. Mohanty ACS Engineering Au 2021 1 (1), -->
<!--     7-38 DOI: 10.1021/acsengineeringau.1c00011 -->
<!-- -   [Zuckerrohr-Verpackungen für die Umwelt -->
<!--     \|Verpacknachhaltig](https://verpacknachhaltig.de/zuckerrohr-verpackung/) -->
<!-- -   [Was ist Bagasse? Unsere Materialkunde zum nachhaltigen Verpackungsmaterial -->
<!--     -packVerde -->
<!--     (pack-verde.com)](https://www.pack-verde.com/blog/at/materialkunde/materialkunde-bagasse/) -->
<!-- -   [Bagasse: Plastikalternative aus Zuckerrohr -->
<!--     -Utopia.de](https://utopia.de/ratgeber/bagasse-plastikalternative-aus-zuckerrohr/) -->
<!-- -   [Was sind die Vor- und Nachteile von Bagasse? - Nachricht -->
<!--     (zc-pak.com)](https://de.zc-pak.com/news/what-is-bagasse-advantages-and-disadvantages-66845834.html#:~:text=Nachteile%20von%20Bagasse%3A%201%201.%20Nicht%20wasserfest%3A%20Bagasse,um%20in%20brauchbare%20Produkte%20umgewandelt%20zu%20werden.%20) -->
<!-- -   [Einweggeschirr: Wie nachhaltig sind Plastikalternativen? - -->
<!--     Utopia.de](https://utopia.de/ratgeber/einweggeschirr-wie-nachhaltig-sind-die-alternativen-zu-plastik/) -->
<!-- -   <https://utopia.de/news/verbraucherzentralen-warnen-bambusgeschirr-plastik/> -->
<!-- -   [Wie nachhaltig ist der Kunststoff? - -->
<!--     Utopia.de](https://utopia.de/ratgeber/pla-wie-nachhaltig-ist-der-kunststoff/#:~:text=Das%20Umweltbundesamt%20best%C3%A4tigt%2C%20dass%20PLA-Kunststoff%20biologisch%20abbaubar%20ist.,zu%20Folie%20verarbeiten%20und%20ist%20fest%20und%20stabil.) -->
<!-- -   [Wie nachhaltig ist PLA Filament wirklich? -->
<!--     -3Dnatives](https://www.3dnatives.com/de/feature-story-3d-druck-material-pla-nachhaltig-230720191/) -->
<!-- -   [Polylactid (PLA) -->
<!--     --Biokunststofftool](https://biokunststofftool.de/werkstoffe/pla-polylactid/#Werkstoffhersteller) -->
<!-- -   Al-Khairy D, Fu W, Alzahmi AS, Twizere JC, Amin SA, Salehi-Ashtiani K, -->
<!--     Mystikou A. Closing the Gap between Bio-Based and Petroleum-Based Plastic -->
<!--     through Bioengineering. Microorganisms. 2022 Nov 23;10(12):2320. doi: -->
<!--     10.3390/microorganisms10122320. PMID: 36557574; PMCID: PMC9787566. -->
<!-- -   [Polymilchsäure](https://link.springer.com/chapter/10.1007/978-3-662-64469-0_35) -->
<!-- -   [Biopolymers-Facts-Statistics-2020](https://www.ifbb-hannover.de/files/IfBB/downloads/faltblaetter_broschueren/f+s/Biopolymers-Facts-Statistics-2020.pdf) -->
<!-- -   [Biokunststoffe - -->
<!--     FraunhoferINT](https://www.int.fraunhofer.de/de/geschaeftsfelder/corporate-technology-foresight/trend-news/biokunststoffe.html) -->
<!-- -   [https://de.statista.com/](https://de.statista.com/statistik/daten/studie/206250/umfrage/landwirtschaftliche-nutzflaeche-in-deutschland/#:~:text=2023%20lag%20die%20landwirtschaftliche%20Nutzfl%C3%A4che%20in%20Deutschland%20bei,dem%20Vorjahr%20blieb%20die%20Agrarfl%C3%A4che%20somit%20nahezu%20konstant). -->
<!-- -   Tanadchangsaeng N, Pattanasupong A. Evaluation of Biodegradabilities of -->
<!--     Biosynthetic Polyhydroxyalkanoates in Thailand Seawater and Toxicity -->
<!--     Assessment of Environmental Safety Levels. Polymers (Basel). 2022 Jan -->
<!--     21;14(3):428. doi: 10.3390/polym14030428. PMID: 35160420; PMCID: PMC8840047. -->
<!-- -   Bioplastic: An Eco‐friendly Alternative of Non‐Biodegradable Plastic June -->
<!--     2023 DOI:10.1002/pi.6555 -->
<!-- -   Serrano-Aguirre L, Prieto MA. Can bioplastics always offer a truly -->
<!--     sustainable alternative to fossil-based plastics? Microb Biotechnol. 2024 -->
<!--     Apr;17(4):e14458. doi: 10.1111/1751-7915.14458. PMID: 38568795; PMCID: -->
<!--     PMC10990045. -->
<!-- -   [Review of recent advances in the biodegradability of polyhydroxyalkanoate -->
<!--     (PHA) bioplastics and their composites - Green Chemistry (RSC -->
<!--     Publishing)](https://pubs.rsc.org/en/content/articlelanding/2020/gc/d0gc01647k#:~:text=PHAs%20such%20as%20poly%20%283-hydroxybutyrate%29%20%28PHB%29%20and%20poly,the%20negativity%20associated%20with%20the%20landfilling%20of%20plastics.) -->
<!-- -   Piemonte, Vincenzo. (2011). 1. V. Piemonte, F. Gironi. Bioplastics and -->
<!--     Petroleum-based Plastics: Strengths and Weaknesses, Energy Sources Part A: -->
<!--     Energy, recovery and Environmental Effect, 2011, 33, 1949-1959. (DOI: -->
<!--     10.1080/15567030903436830). Energy Sources Part A Recovery Utilization and -->
<!--     Environmental Effects. -->
<!-- -   [PET, PE und PVC: Das müssen Sie über Kunststoffe wissen \| -->
<!--     Verbraucherzentrale.de](https://www.verbraucherzentrale.de/wissen/lebensmittel/lebensmittelproduktion/kunststoffe-7035) -->
<!-- -   [Polyethylenterephthalat -->
<!--     (chemie.de)](https://www.chemie.de/lexikon/Polyethylenterephthalat.html) -->
<!-- -   Soong, Y.-H.V.; Sobkowicz, M.J.; Xie, D. Recent Advances in Biological -->
<!--     Recycling of Polyethylene Terephthalate (PET) Plastic Wastes. Bioengineering -->
<!--     2022, 9, 98. https://doi.org/10.3390/bioengineering9030098 -->
<!-- -   ["Nein zur Wegwerfgesellschaft" -- 5-Punkte-Plan des -->
<!--     Bundesumweltministeriums für weniger Plastik und mehr -->
<!--     Recycling(bmuv.de)](https://www.bmuv.de/fileadmin/Daten_BMU/Download_PDF/Abfallwirtschaft/181123_5_punkte_plan_plastik_bf.pdf) -->
<!-- -   [Plastikmüll Statistiken in Deutschland, weltweit und im Meer -->
<!--     (2023)(aktivbewusst.de)](https://aktivbewusst.de/plastikmuell-statistiken-deutschland-weltweit/#t-1691126514865) -->
<!-- -   [So werden Plastikflaschen wiederverwertet -->
<!--     -quarks.de](https://www.quarks.de/umwelt/muell/so-werden-plastikflaschen-wiederverwertet/) -->
<!-- -   [EU packaging waste generation with record increase - Eurostat -->
<!--     (europa.eu)](https://ec.europa.eu/eurostat/web/products-eurostat-news/-/ddn-20231019-1) -->
<!-- -   [Plastikatlas 2019 -->
<!--     (boell.de)](https://www.boell.de/sites/default/files/2019-11/Plastikatlas_2019_3._Auflage.pdf) -->
<!-- -   171025-nabu-01b_studie_verwendung-und-recycling-pet-deutschland.pdf(https://www.nabu.de/imperia/md/content/nabude/veranstaltungen/171025-nabu-01b_studie_verwendung-und-recycling-pet-deutschland.pdf) -->
<!-- -   [Landwirtschaftszählung 2020 - Statistisches Bundesamt -->
<!--     (destatis.de)](https://www.destatis.de/DE/Themen/Branchen-Unternehmen/Landwirtschaft-Forstwirtschaft-Fischerei/Landwirtschaftszaehlung2020/_inhalt.html) -->
<!-- -   [PET: Produktion in Deutschland bis 2023 \| -->
<!--     Statista](https://de.statista.com/statistik/daten/studie/1285091/umfrage/polyethylenterephthalat-produktion-in-deutschland/#:~:text=Im%20Jahr%202023%20wurden%20in%20Deutschland%20seitens%20der,vorwiegend%20bei%20der%20Produktion%20von%20Kunststoffflaschen%20verwendet%20wird.) -->
<!-- -   [PET global production 2020 -->
<!--     \|Statista](https://www.statista.com/statistics/650191/global-polyethylene-terephthalate-production-outlook/) -->
<!-- -   https://www.umweltbundesamt.de/biobasierte-biologisch-abbaubare-kunststoffe#310-bieten-verpackungen-aus-biologisch-abbaubaren-kunststoffen-vorteile -->
<!-- -   [Material_choices_211020.pdf -->
<!--     (greentechknowledgehub.de)](https://greentechknowledgehub.de/sites/default/files/2021-10/Material_choices_211020.pdf) -->
<!-- -   Energy Inputs on the Production of Plastic Products September 2022Journal of -->
<!--     Ecological Engineering 23(9):146-156 23(9):146-156 -->
<!--     DOI:10.12911/22998993/151815 -->
<!-- -   [Effiziente Biokunststoff Herstellung mit Industriezentrifugen -->
<!--     (flottweg.com)](https://www.flottweg.com/de/anwendungen/pharmazie-und-biotechnologie/biokunststoff/) -->


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../energy-sources/part_energy-sources.html" class="pagination-link" aria-label="Energiewandler">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Energiewandler</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../summary.html" class="pagination-link" aria-label="Zusammenfassung">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Zusammenfassung</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>