on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./markdown
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
      
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: scheme-basic xetex standalone pgf etoolbox

      - name: Install Dev Dependencies
        run: |
          sudo apt update
          sudo apt install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev \
            libfontconfig1-dev libcurl4-openssl-dev libharfbuzz-dev libfreetype-dev libfribidi-dev \
            librsvg2-bin poppler-utils latexmk fonts-noto-core 
          
        # with:
        #   cache-version: 1
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ./markdown
          cache-version: 1

      - name: Convert Images
        run: bash convert-images.sh

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}